// SPDX-FileCopyrightText: 2026 Vladislav Tomilov
// SPDX-License-Identifier: GPL-3.0-or-later

package kinetickk.ball.gameplay.interaction.localization

internal fun englishGameplayText(key: GameplayText): String = when (key) {
    GameplayText.Gameplay -> "KINETICKK gameplay"
    GameplayText.Build -> "I · BUILD"
    GameplayText.DashDescription -> "Dash"
    GameplayText.OfflineState -> "offline"
    GameplayText.ReadyState -> "ready"
    GameplayText.CoolingState -> "cooling"
    GameplayText.PauseDescription -> "Pause game"
    GameplayText.ResumeDescription -> "Resume game"
    GameplayText.SettingsDescription -> "Open gameplay settings"
    GameplayText.ExitDescription -> "Exit to home"
    GameplayText.RestartDescription -> "Restart run"
    GameplayText.RebirthDescription -> "Start next rebirth cycle"
    GameplayText.PerformanceDescription -> "Performance metrics"
    GameplayText.OnState -> "on"
    GameplayText.OffState -> "off"
    GameplayText.BrakeDescription -> "Brake"
    GameplayText.BrakeAction -> "Toggle brake"
    GameplayText.PressedState -> "pressed"
    GameplayText.ReleasedState -> "released"
    GameplayText.Core -> "CORE // {0}"
    GameplayText.LevelData -> "LV {0}   DATA {1}/{2}"
    GameplayText.Integrity -> "INTEGRITY {0}"
    GameplayText.Shield -> "SHIELD {0}/{1}"
    GameplayText.HeatOffline -> "HEAT // OFFLINE"
    GameplayText.Heat -> "HEAT"
    GameplayText.PhaseCompact -> "R{0} // DRIFT > ARCHITECT"
    GameplayText.Phase -> "REBIRTH {0} // DRIFT  >  SURGE  >  ARCHITECT"
    GameplayText.OverdriveActive -> "OVERDRIVE ACTIVE"
    GameplayText.Overdrive -> "OVERDRIVE {0}%"
    GameplayText.PolarityWarning -> "POLARITY {0}% // TURN OR RECENTER"
    GameplayText.Polarity -> "POLARITY {0}%"
    GameplayText.WeaponMastery -> "LV {0} // {1}"
    GameplayText.NextWeaponMastery -> "LV {0} // {1} > {2} {3}"
    GameplayText.Velocity -> "{0} // {1} u/s"
    GameplayText.MassCombo -> "MASS {0}  COMBO x{1}"
    GameplayText.PowerItemsMatter -> "PWR {0}×  ITEMS {1}  MATTER {2}"
    GameplayText.Chain -> "CHAIN x{0}"
    GameplayText.SingularityProximity -> "SINGULARITY PROXIMITY"
    GameplayText.Impact -> "IMPACT // {0}"
    GameplayText.Hp -> "HP {0}/{1}"
    GameplayText.ShieldHeat -> "SHIELD {0} // HEAT {1}"
    GameplayText.HeatPowerRelics -> "HEAT {0} · PWR {1}× · RELICS {2}/4"
    GameplayText.RebirthMatter -> "R{0} // {1} MATTER"
    GameplayText.Brake -> "BRAKE"
    GameplayText.Hold -> "HOLD"
    GameplayText.Dash -> "DASH"
    GameplayText.Off -> "OFF"
    GameplayText.Ready -> "READY"
    GameplayText.Wait -> "WAIT"
    GameplayText.PerformanceShort -> "PERF"
    GameplayText.Metrics -> "METRICS"
    GameplayText.Pause -> "PAUSE"
    GameplayText.SingularityClose -> "SINGULARITY CLOSE"
    GameplayText.RelicMatrix -> "RELIC MATRIX {0}/{1}"
    GameplayText.Offline -> "OFFLINE"
    GameplayText.Cooling -> "COOLING"
    GameplayText.Wave -> "WAVE {0}%"
    GameplayText.BarrierRam -> "BARRIER {0} · RAM {1}%"
    GameplayText.DashMarkHit -> "DASH → MARK → HIT"
    GameplayText.RingDeadZone -> "RING {0} · DEAD ZONE"
    GameplayText.ParryWindow -> "PARRY WINDOW"
    GameplayText.Parry -> "PARRY {0}%"
    GameplayText.Lattice -> "LATTICE {0}/4"
    GameplayText.SystemPaused -> "SYSTEM PAUSED"
    GameplayText.Resume -> "RESUME"
    GameplayText.Settings -> "SETTINGS"
    GameplayText.PerformanceMetrics -> "PERFORMANCE METRICS"
    GameplayText.ReturnHome -> "RETURN TO HOME"
    GameplayText.ResumeKey -> "RESUME [P / ESC]"
    GameplayText.SettingsKey -> "SETTINGS [S]"
    GameplayText.ReturnMenu -> "RETURN TO MENU"
    GameplayText.RunConquered -> "RUN CONQUERED"
    GameplayText.ArchitectFallen -> "THE ARCHITECT HAS FALLEN"
    GameplayText.SingularityRemembers -> "THE SINGULARITY REMEMBERS"
    GameplayText.Time -> "TIME {0}"
    GameplayText.Kills -> "KILLS {0}"
    GameplayText.Matter -> "MATTER {0}"
    GameplayText.WeaponLevel -> "WEAPON {0} // LV {1}"
    GameplayText.DiscoveriesPeak -> "ITEMS {0}   DISCOVERIES {1}/{2}   PEAK {3}"
    GameplayText.ReenterKey -> "RE-ENTER [R]"
    GameplayText.RebirthNextKey -> "REBIRTH [B] // NEXT CYCLE"
    GameplayText.CoreSelectHint -> "TAP BELOW FOR CORE SELECT // BANK {0}"
    GameplayText.RunStats -> "TIME {0} // KILLS {1} // MATTER {2}"
    GameplayText.WeaponBank -> "{0} LV {1} // BANK {2}"
    GameplayText.Reenter -> "RE-ENTER"
    GameplayText.RebirthNext -> "REBIRTH // NEXT CYCLE"
    GameplayText.BuildUpdated -> "Build updated"
    GameplayText.WeaponTotem -> "WEAPON TOTEM"
    GameplayText.Slot -> "SLOT {0}"
    GameplayText.Stack -> "STACK {0}/{1}"
    GameplayText.CurrentWeaponLevel -> "CURRENT WEAPON // LV {0} → {1}"
    GameplayText.WeaponPicker -> "OPEN WEAPON PICKER"
    GameplayText.RunWeapon -> "RUN WEAPON // {0}"
    GameplayText.Incoming -> "INCOMING // {0}\n{1}\n{2}"
    GameplayText.SalvageResonance -> "SALVAGE RESONANCE"
    GameplayText.MeldRank -> "MELD // R{0} → R{1}"
    GameplayText.BindMatrix -> "BIND TO MATRIX"
    GameplayText.MeldSlot -> "MELD SIGNAL INTO A SLOT"
    GameplayText.ReplaceSlot -> "REPLACE SLOT {0}"
    GameplayText.SalvageExcess -> "SALVAGE EXCESS"
    GameplayText.ChooseArtifact -> "CHOOSE AN ARTIFACT"
    GameplayText.TotemResonance -> "TOTEM RESONANCE"
    GameplayText.WeaponSynchronization -> "WEAPON SYNCHRONIZATION"
    GameplayText.RelicIntercept -> "RELIC INTERCEPT"
    GameplayText.RelicMeld -> "RELIC MELD"
    GameplayText.RelicRebind -> "RELIC REBIND"
    GameplayText.TimeSuspended -> "TIME IS SUSPENDED"
    GameplayText.AmplifyOrRecalibrate -> "AMPLIFY THE CURRENT SYSTEM OR RECALIBRATE"
    GameplayText.NextRunWeapon -> "SELECT THE NEXT RUN WEAPON"
    GameplayText.MatrixFull -> "MATRIX FULL // CLAIM A SIGNAL OR MELD IT INTO THE MATRIX"
    GameplayText.EliteSignalCaptured -> "ELITE SIGNAL CAPTURED // RELICS SYNCHRONIZE WITH EVERY WEAPON"
    GameplayText.SelectMeldTarget -> "SELECT A TARGET // THE CHOSEN RELIC GAINS ONE RANK"
    GameplayText.SelectReplaceSlot -> "SELECT A SLOT // ITS CURRENT RELIC WILL BE REPLACED"
    GameplayText.Reroll -> "REROLL [Q] · {0}"
    GameplayText.SelectChoice -> "Select choice {0}: {1}"
    GameplayText.Select -> "SELECT [{0}]"
    GameplayText.ScrollableRewards -> "Scrollable reward details"
    GameplayText.PointTimer -> "{0} // {1}s"
    GameplayText.PointProgress -> "{0} // {1}% // {2}s"
    GameplayText.PerformanceTitle -> "PERFORMANCE // F3 TOGGLE + RESET // ROLLING WINDOW"
    GameplayText.PerformanceCompactTitle -> "PERFORMANCE // TAP PERF // ROLLING"
    GameplayText.Frame -> "FRAME"
    GameplayText.Dispatch -> "DISPATCH"
    GameplayText.Canvas -> "CANVAS"
    GameplayText.Rate -> "FPS {0}  1% LOW {1}"
    GameplayText.Entities -> "ENTITY CUR/PEAK"
    GameplayText.EnemyCounts -> "  E {0}/{1}"
    GameplayText.ProjectileCounts -> "  P {0}/{1}"
    GameplayText.PickupCounts -> "  PICK {0}/{1}"
    GameplayText.TrailCounts -> "  TRAIL {0}/{1}"
    GameplayText.CompactFrame -> "FRM P50 {0}"
    GameplayText.Max -> " MAX {0}"
    GameplayText.CompactSamples -> "N {0} W {1}"
    GameplayText.CompactPipeline -> " | PIPE P50 {0} P95 {1}"
    GameplayText.CompactDraw -> "DRAW P50 {0} P95 {1}"
    GameplayText.CompactRate -> " | FPS {0} LOW {1}"
    GameplayText.CompactEnemies -> " | E {0}/{1}"
    GameplayText.CompactProjectiles -> " PRJ {0}/{1}"
    GameplayText.CompactPickups -> "PICK {0}/{1}"
    GameplayText.CompactTrail -> " TRAIL {0}/{1}"
    GameplayText.Milliseconds -> "{0} ms"
    GameplayText.MaxRegular -> "  MAX {0}"
    GameplayText.Samples -> "  N {0}  WIN {1}"
}
