// SPDX-FileCopyrightText: 2026 Vladislav Tomilov
// SPDX-License-Identifier: GPL-3.0-or-later

package kinetickk.ball.gameplay.interaction.localization

internal fun englishGameplayText(key: GameplayText): String = when (key) {
    GameplayText.NewDiscovery -> "New!"
    GameplayText.DetailedStatistics -> "Run statistics"
    GameplayText.CombatStatistics -> "Combat"
    GameplayText.LootStatistics -> "Collection & growth"
    GameplayText.EnemiesDestroyed -> "Enemies destroyed"
    GameplayText.ElitesDestroyed -> "Elites destroyed"
    GameplayText.DamageDealt -> "Damage dealt"
    GameplayText.DamageTaken -> "Integrity lost"
    GameplayText.DamageAbsorbed -> "Shield & barrier absorbed"
    GameplayText.BestCombo -> "Best kill streak"
    GameplayText.MatterEarned -> "Matter earned"
    GameplayText.DataCollected -> "Data gained"
    GameplayText.PickupsCollected -> "Pickups collected"
    GameplayText.KeysCollected -> "Keys found"
    GameplayText.ArtifactsAcquired -> "Artifacts acquired"
    GameplayText.LevelReached -> "Level reached"
    GameplayText.RunDuration -> "Run time"
    GameplayText.RunRecord -> "Run report"
    GameplayText.DamageAccountingHint -> "Damage counts integrity actually removed, excluding overkill."
    GameplayText.NoStatChange -> "Stats already at their limits"
    GameplayText.AffectedComponent -> "Improves"
    GameplayText.FamilyResonance -> "Family resonance"
    GameplayText.WeaponInteraction -> "Weapon effect"
    GameplayText.SynergyConnection -> "Synergy"
    GameplayText.Gameplay -> "KINETICKK gameplay"
    GameplayText.Build -> "Build"
    GameplayText.DashDescription -> "Dash"
    GameplayText.OfflineState -> "offline"
    GameplayText.ReadyState -> "ready"
    GameplayText.CoolingState -> "cooling"
    GameplayText.PauseDescription -> "Pause game"
    GameplayText.ResumeDescription -> "Resume game"
    GameplayText.SettingsDescription -> "Open gameplay settings"
    GameplayText.ExitDescription -> "Exit to home"
    GameplayText.PerformanceDescription -> "Performance metrics"
    GameplayText.OnState -> "on"
    GameplayText.OffState -> "off"
    GameplayText.BrakeDescription -> "Brake"
    GameplayText.BrakeAction -> "Toggle brake"
    GameplayText.PressedState -> "pressed"
    GameplayText.ReleasedState -> "released"
    GameplayText.SystemPaused -> "Paused"
    GameplayText.Resume -> "Resume"
    GameplayText.Settings -> "Settings"
    GameplayText.PerformanceMetrics -> "Performance"
    GameplayText.ReturnHome -> "Main menu"
    GameplayText.ArchitectFallen -> "The Architect has fallen"
    GameplayText.Reenter -> "Play again"
    GameplayText.RebirthNext -> "Next cycle"
    GameplayText.BuildUpdated -> "Build updated"
    GameplayText.WeaponTotem -> "Weapon totem"
    GameplayText.ChooseArtifact -> "Upgrade"
    GameplayText.TotemResonance -> "Upgrade"
    GameplayText.WeaponSynchronization -> "Weapon"
    GameplayText.RelicIntercept -> "Relic"
    GameplayText.RelicMeld -> "Merge"
    GameplayText.RelicRebind -> "Replace relic"
    GameplayText.SelectChoice -> "Select choice {0}: {1}"
    GameplayText.ScrollableRewards -> "Scrollable reward details"
    GameplayText.PerformanceTitle -> "Performance"
    GameplayText.Frame -> "FRAME"
    GameplayText.Dispatch -> "DISPATCH"
    GameplayText.Canvas -> "CANVAS"
    GameplayText.Rate -> "FPS {0}  1% LOW {1}"
    GameplayText.Entities -> "ENTITY CUR/PEAK"
    GameplayText.EnemyCounts -> "  E {0}/{1}"
    GameplayText.ProjectileCounts -> "  P {0}/{1}"
    GameplayText.PickupCounts -> "  PICK {0}/{1}"
    GameplayText.TrailCounts -> "  TRAIL {0}/{1}"
    GameplayText.CompactFrame -> "FRM P50 {0}"
    GameplayText.Max -> " MAX {0}"
    GameplayText.CompactSamples -> "N {0} W {1}"
    GameplayText.CompactPipeline -> " | PIPE P50 {0} P95 {1}"
    GameplayText.CompactDraw -> "DRAW P50 {0} P95 {1}"
    GameplayText.CompactRate -> " | FPS {0} LOW {1}"
    GameplayText.CompactEnemies -> " | E {0}/{1}"
    GameplayText.CompactProjectiles -> " PRJ {0}/{1}"
    GameplayText.CompactPickups -> "PICK {0}/{1}"
    GameplayText.CompactTrail -> " TRAIL {0}/{1}"
    GameplayText.Milliseconds -> "{0} ms"
    GameplayText.MaxRegular -> "  MAX {0}"
    GameplayText.Samples -> "  N {0}  WIN {1}"
}
