// SPDX-FileCopyrightText: 2026 Vladislav Tomilov
// SPDX-License-Identifier: GPL-3.0-or-later

package kinetickk.ball.gameplay.interaction.localization

import kinetickk.foundation.common.localization.TextResource

internal enum class GameplayText : TextResource {
    NewDiscovery,
    NoStatChange,
    AffectedComponent,
    FamilyResonance,
    WeaponInteraction,
    SynergyConnection,
    Gameplay,
    Build,
    DashDescription,
    OfflineState,
    ReadyState,
    CoolingState,
    PauseDescription,
    ResumeDescription,
    SettingsDescription,
    ExitDescription,
    PerformanceDescription,
    OnState,
    OffState,
    BrakeDescription,
    BrakeAction,
    PressedState,
    ReleasedState,
    SystemPaused,
    Resume,
    Settings,
    PerformanceMetrics,
    ReturnHome,
    ArchitectFallen,
    DetailedStatistics,
    CombatStatistics,
    LootStatistics,
    EnemiesDestroyed,
    ElitesDestroyed,
    DamageDealt,
    DamageTaken,
    DamageAbsorbed,
    BestCombo,
    MatterEarned,
    DataCollected,
    PickupsCollected,
    KeysCollected,
    ArtifactsAcquired,
    LevelReached,
    RunDuration,
    RunRecord,
    DamageAccountingHint,
    Reenter,
    RebirthNext,
    BuildUpdated,
    WeaponTotem,
    ChooseArtifact,
    TotemResonance,
    WeaponSynchronization,
    RelicIntercept,
    RelicMeld,
    RelicRebind,
    SelectChoice,
    ScrollableRewards,
    PerformanceTitle,
    Frame,
    Dispatch,
    Canvas,
    Rate,
    Entities,
    EnemyCounts,
    ProjectileCounts,
    PickupCounts,
    TrailCounts,
    CompactFrame,
    Max,
    CompactSamples,
    CompactPipeline,
    CompactDraw,
    CompactRate,
    CompactEnemies,
    CompactProjectiles,
    CompactPickups,
    CompactTrail,
    Milliseconds,
    MaxRegular,
    Samples;

    override val english: String get() = englishGameplayText(this)
    override val russian: String get() = russianGameplayText(this)
}
