// SPDX-FileCopyrightText: 2026 Vladislav Tomilov
// SPDX-License-Identifier: GPL-3.0-or-later

package kinetickk.ball.gameplay.interaction.localization

internal fun russianGameplayText(key: GameplayText): String = when (key) {
    GameplayText.NewDiscovery -> "Новый!"
    GameplayText.DetailedStatistics -> "Статистика забега"
    GameplayText.CombatStatistics -> "Бой"
    GameplayText.LootStatistics -> "Сбор и развитие"
    GameplayText.EnemiesDestroyed -> "Врагов уничтожено"
    GameplayText.ElitesDestroyed -> "Элитных врагов"
    GameplayText.DamageDealt -> "Нанесено урона"
    GameplayText.DamageTaken -> "Потеряно прочности"
    GameplayText.DamageAbsorbed -> "Поглощено щитом и барьером"
    GameplayText.BestCombo -> "Лучшая серия убийств"
    GameplayText.MatterEarned -> "Материи получено"
    GameplayText.DataCollected -> "Данных получено"
    GameplayText.PickupsCollected -> "Предметов подобрано"
    GameplayText.KeysCollected -> "Ключей найдено"
    GameplayText.ArtifactsAcquired -> "Артефактов получено"
    GameplayText.LevelReached -> "Достигнутый уровень"
    GameplayText.RunDuration -> "Время забега"
    GameplayText.RunRecord -> "Итоги забега"
    GameplayText.DamageAccountingHint -> "Урон учитывает снятую прочность, без избыточного урона."
    GameplayText.NoStatChange -> "Характеристики уже на пределе"
    GameplayText.AffectedComponent -> "Усиливает"
    GameplayText.FamilyResonance -> "Резонанс семейства"
    GameplayText.WeaponInteraction -> "Эффект оружия"
    GameplayText.SynergyConnection -> "Синергия"
    GameplayText.Gameplay -> "Игра KINETICKK"
    GameplayText.Build -> "Сборка"
    GameplayText.DashDescription -> "Рывок"
    GameplayText.OfflineState -> "недоступен"
    GameplayText.ReadyState -> "готов"
    GameplayText.CoolingState -> "остывает"
    GameplayText.PauseDescription -> "Приостановить игру"
    GameplayText.ResumeDescription -> "Продолжить игру"
    GameplayText.SettingsDescription -> "Открыть настройки игры"
    GameplayText.ExitDescription -> "Выйти в главное меню"
    GameplayText.PerformanceDescription -> "Показатели производительности"
    GameplayText.OnState -> "включены"
    GameplayText.OffState -> "выключены"
    GameplayText.BrakeDescription -> "Тормоз"
    GameplayText.BrakeAction -> "Переключить тормоз"
    GameplayText.PressedState -> "нажат"
    GameplayText.ReleasedState -> "отпущен"
    GameplayText.SystemPaused -> "Пауза"
    GameplayText.Resume -> "Продолжить"
    GameplayText.Settings -> "Настройки"
    GameplayText.PerformanceMetrics -> "Производительность"
    GameplayText.ReturnHome -> "В меню"
    GameplayText.ArchitectFallen -> "Архитектор повержен"
    GameplayText.Reenter -> "Ещё раз"
    GameplayText.RebirthNext -> "Следующий цикл"
    GameplayText.BuildUpdated -> "Сборка обновлена"
    GameplayText.WeaponTotem -> "Оружейный тотем"
    GameplayText.ChooseArtifact -> "Улучшение"
    GameplayText.TotemResonance -> "Улучшение"
    GameplayText.WeaponSynchronization -> "Оружие"
    GameplayText.RelicIntercept -> "Реликвия"
    GameplayText.RelicMeld -> "Слияние"
    GameplayText.RelicRebind -> "Замена реликвии"
    GameplayText.SelectChoice -> "Выбрать вариант {0}: {1}"
    GameplayText.ScrollableRewards -> "Прокручиваемое описание награды"
    GameplayText.PerformanceTitle -> "Производительность"
    GameplayText.Frame -> "КАДР"
    GameplayText.Dispatch -> "ОБРАБОТКА"
    GameplayText.Canvas -> "ОТРИСОВКА"
    GameplayText.Rate -> "КАДР/С {0}  1% МИН {1}"
    GameplayText.Entities -> "ОБЪЕКТЫ ТЕК/ПИК"
    GameplayText.EnemyCounts -> "  ВРАГ {0}/{1}"
    GameplayText.ProjectileCounts -> "  СНР {0}/{1}"
    GameplayText.PickupCounts -> "  ПОДБ {0}/{1}"
    GameplayText.TrailCounts -> "  СЛЕД {0}/{1}"
    GameplayText.CompactFrame -> "КДР P50 {0}"
    GameplayText.Max -> " МАКС {0}"
    GameplayText.CompactSamples -> "N {0} О {1}"
    GameplayText.CompactPipeline -> " | ОБР P50 {0} P95 {1}"
    GameplayText.CompactDraw -> "РИС P50 {0} P95 {1}"
    GameplayText.CompactRate -> " | К/С {0} МИН {1}"
    GameplayText.CompactEnemies -> " | ВР {0}/{1}"
    GameplayText.CompactProjectiles -> " СНР {0}/{1}"
    GameplayText.CompactPickups -> "ПОДБ {0}/{1}"
    GameplayText.CompactTrail -> " СЛЕД {0}/{1}"
    GameplayText.Milliseconds -> "{0} мс"
    GameplayText.MaxRegular -> "  МАКС {0}"
    GameplayText.Samples -> "  N {0}  ОКНО {1}"
}
