// SPDX-FileCopyrightText: 2026 Vladislav Tomilov
// SPDX-License-Identifier: GPL-3.0-or-later

package kinetickk.ball.gameplay.interaction.localization

internal fun russianGameplayText(key: GameplayText): String = when (key) {
    GameplayText.DetailedStatistics -> "Статистика забега"
    GameplayText.CombatStatistics -> "БОЙ"
    GameplayText.LootStatistics -> "СБОР И РАЗВИТИЕ"
    GameplayText.EnemiesDestroyed -> "Врагов уничтожено"
    GameplayText.ElitesDestroyed -> "Элитных врагов"
    GameplayText.DamageDealt -> "Нанесено урона"
    GameplayText.DamageTaken -> "Потеряно прочности"
    GameplayText.DamageAbsorbed -> "Поглощено щитом и барьером"
    GameplayText.BestCombo -> "Лучшая серия убийств"
    GameplayText.MatterEarned -> "Материи получено"
    GameplayText.DataCollected -> "Данных получено"
    GameplayText.PickupsCollected -> "Предметов подобрано"
    GameplayText.KeysCollected -> "Ключей найдено"
    GameplayText.ArtifactsAcquired -> "Артефактов получено"
    GameplayText.LevelReached -> "Достигнутый уровень"
    GameplayText.RunDuration -> "Время забега"
    GameplayText.RunRecord -> "ИТОГИ ЗАБЕГА"
    GameplayText.DamageAccountingHint -> "Урон учитывает снятую прочность, без избыточного урона."
    GameplayText.StackChange -> "КОПИИ {0} → {1}/{2}"
    GameplayText.PreviewAfterSlot -> "Сравнение после выбора слота"
    GameplayText.NoStatChange -> "Характеристики уже на пределе"
    GameplayText.AffectedComponent -> "Усиливает"
    GameplayText.FamilyResonance -> "Резонанс семейства"
    GameplayText.WeaponInteraction -> "Эффект оружия"
    GameplayText.SynergyConnection -> "Синергия"
    GameplayText.RewardConnections -> "ВЗАИМОДЕЙСТВИЯ"
    GameplayText.RewardTranspose -> "Каждые 6 попаданий: перенос цели через ядро"
    GameplayText.RewardRewind -> "При перегрузке: сброс перезарядки и −10 нагрева"
    GameplayText.Gameplay -> "Игра KINETICKK"
    GameplayText.Build -> "Сборка · I"
    GameplayText.LevelShort -> "Ур. {0}"
    GameplayText.DashDescription -> "Рывок"
    GameplayText.OfflineState -> "недоступен"
    GameplayText.ReadyState -> "готов"
    GameplayText.CoolingState -> "остывает"
    GameplayText.PauseDescription -> "Приостановить игру"
    GameplayText.ResumeDescription -> "Продолжить игру"
    GameplayText.SettingsDescription -> "Открыть настройки игры"
    GameplayText.ExitDescription -> "Выйти в главное меню"
    GameplayText.RestartDescription -> "Начать забег заново"
    GameplayText.RebirthDescription -> "Начать следующий цикл перерождения"
    GameplayText.PerformanceDescription -> "Показатели производительности"
    GameplayText.OnState -> "включены"
    GameplayText.OffState -> "выключены"
    GameplayText.BrakeDescription -> "Тормоз"
    GameplayText.BrakeAction -> "Переключить тормоз"
    GameplayText.PressedState -> "нажат"
    GameplayText.ReleasedState -> "отпущен"
    GameplayText.Core -> "ЯДРО // {0}"
    GameplayText.LevelData -> "УР. {0}   ДАННЫЕ {1}/{2}"
    GameplayText.Integrity -> "ПРОЧНОСТЬ {0}"
    GameplayText.Shield -> "ЩИТ {0}/{1}"
    GameplayText.HeatOffline -> "ПЕРЕГРЕВ // СБОЙ"
    GameplayText.Heat -> "НАГРЕВ"
    GameplayText.PhaseCompact -> "Ц{0} // ДРЕЙФ > АРХИТЕКТОР"
    GameplayText.Phase -> "ЦИКЛ {0} // ДРЕЙФ  >  РАЗГОН  >  АРХИТЕКТОР"
    GameplayText.OverdriveActive -> "Перегрузка"
    GameplayText.Overdrive -> "ПЕРЕГРУЗКА {0}%"
    GameplayText.PolarityWarning -> "Уведите курсор от края · {0}%"
    GameplayText.Polarity -> "ПОЛЯРНОСТЬ {0}%"
    GameplayText.WeaponMastery -> "УР. {0} // {1}"
    GameplayText.NextWeaponMastery -> "УР. {0} // {1} > {2} {3}"
    GameplayText.Velocity -> "{0} // {1} ед/с"
    GameplayText.MassCombo -> "МАССА {0}  КОМБО x{1}"
    GameplayText.PowerItemsMatter -> "МОЩЬ {0}×  ПРЕДМ. {1}  МАТЕРИЯ {2}"
    GameplayText.Chain -> "ЦЕПОЧКА x{0}"
    GameplayText.SingularityProximity -> "СИНГУЛЯРНОСТЬ РЯДОМ"
    GameplayText.Impact -> "УДАР // {0}"
    GameplayText.Hp -> "ОЗ {0}/{1}"
    GameplayText.ShieldHeat -> "ЩИТ {0} // НАГРЕВ {1}"
    GameplayText.HeatPowerRelics -> "НАГРЕВ {0} · МОЩЬ {1}× · РЕЛИКВИИ {2}/4"
    GameplayText.RebirthMatter -> "Ц{0} // {1} МАТЕРИИ"
    GameplayText.Brake -> "ТОРМОЗ"
    GameplayText.Hold -> "ДЕРЖАТЬ"
    GameplayText.Dash -> "РЫВОК"
    GameplayText.Off -> "ВЫКЛ"
    GameplayText.Ready -> "ГОТОВ"
    GameplayText.Wait -> "ЖДИТЕ"
    GameplayText.PerformanceShort -> "ДИАГН."
    GameplayText.Metrics -> "МЕТРИКИ"
    GameplayText.Pause -> "ПАУЗА"
    GameplayText.SingularityClose -> "Отведите цель от ядра"
    GameplayText.RelicMatrix -> "МАТРИЦА РЕЛИКВИЙ {0}/{1}"
    GameplayText.Offline -> "НЕДОСТУПЕН"
    GameplayText.Cooling -> "ОСТЫВАЕТ"
    GameplayText.Wave -> "ВОЛНА {0}%"
    GameplayText.BarrierRam -> "БАРЬЕР {0} · ТАРАН {1}%"
    GameplayText.DashMarkHit -> "РЫВОК → МЕТКА → УДАР"
    GameplayText.RingDeadZone -> "КОЛЬЦО {0} · МЁРТВАЯ ЗОНА"
    GameplayText.ParryWindow -> "ОКНО ПАРИРОВАНИЯ"
    GameplayText.Parry -> "ПАРИРОВАНИЕ {0}%"
    GameplayText.Lattice -> "РЕШЁТКА {0}/4"
    GameplayText.SystemPaused -> "Пауза"
    GameplayText.Resume -> "Продолжить"
    GameplayText.Settings -> "Настройки"
    GameplayText.PerformanceMetrics -> "Производительность"
    GameplayText.ReturnHome -> "В меню"
    GameplayText.ResumeKey -> "ПРОДОЛЖИТЬ [P / ESC]"
    GameplayText.SettingsKey -> "НАСТРОЙКИ [S]"
    GameplayText.ReturnMenu -> "ВЕРНУТЬСЯ В МЕНЮ"
    GameplayText.RunConquered -> "Победа"
    GameplayText.ArchitectFallen -> "АРХИТЕКТОР ПОВЕРЖЕН"
    GameplayText.SingularityRemembers -> "Забег завершён"
    GameplayText.Time -> "ВРЕМЯ {0}"
    GameplayText.Kills -> "УБИЙСТВА {0}"
    GameplayText.Matter -> "МАТЕРИЯ {0}"
    GameplayText.WeaponLevel -> "{0} · Ур. {1}"
    GameplayText.DiscoveriesPeak -> "ПРЕДМЕТЫ {0}   ОТКРЫТО {1}/{2}   ПИК {3}"
    GameplayText.ReenterKey -> "НОВЫЙ ЗАБЕГ [R]"
    GameplayText.RebirthNextKey -> "ПЕРЕРОЖДЕНИЕ [B] // НОВЫЙ ЦИКЛ"
    GameplayText.CoreSelectHint -> "НАЖМИТЕ НИЖЕ ДЛЯ ВЫБОРА ЯДРА // БАНК {0}"
    GameplayText.RunStats -> "ВРЕМЯ {0} // УБИЙСТВА {1} // МАТЕРИЯ {2}"
    GameplayText.WeaponBank -> "{0} УР. {1} // БАНК {2}"
    GameplayText.Reenter -> "Ещё раз"
    GameplayText.RebirthNext -> "Следующий цикл"
    GameplayText.BuildUpdated -> "Сборка обновлена"
    GameplayText.WeaponTotem -> "ОРУЖЕЙНЫЙ ТОТЕМ"
    GameplayText.Slot -> "ЯЧЕЙКА {0}"
    GameplayText.Stack -> "КОПИИ {0}/{1}"
    GameplayText.CurrentWeaponLevel -> "ТЕКУЩЕЕ ОРУЖИЕ // УР. {0} → {1}"
    GameplayText.WeaponPicker -> "ОТКРЫТЬ ВЫБОР ОРУЖИЯ"
    GameplayText.RunWeapon -> "ОРУЖИЕ ЗАБЕГА // {0}"
    GameplayText.Incoming -> "НОВАЯ РЕЛИКВИЯ // {0}\n{1}\n{2}"
    GameplayText.SalvageResonance -> "ИЗВЛЕЧЬ РЕЗОНАНС"
    GameplayText.MeldRank -> "СЛИЯНИЕ // Р{0} → Р{1}"
    GameplayText.BindMatrix -> "СВЯЗАТЬ С МАТРИЦЕЙ"
    GameplayText.MeldSlot -> "СЛИТЬ СИГНАЛ С РЕЛИКВИЕЙ"
    GameplayText.ReplaceSlot -> "ЗАМЕНИТЬ ЯЧЕЙКУ {0}"
    GameplayText.SalvageExcess -> "ИЗВЛЕЧЬ ИЗЛИШЕК"
    GameplayText.ChooseArtifact -> "Улучшение"
    GameplayText.TotemResonance -> "Улучшение"
    GameplayText.WeaponSynchronization -> "Оружие"
    GameplayText.RelicIntercept -> "Реликвия"
    GameplayText.RelicMeld -> "Слияние"
    GameplayText.RelicRebind -> "Замена реликвии"
    GameplayText.TimeSuspended -> "Выберите один вариант"
    GameplayText.AmplifyOrRecalibrate -> "Усилить оружие или сменить его"
    GameplayText.NextRunWeapon -> "Выберите оружие"
    GameplayText.MatrixFull -> "Нет свободных ячеек"
    GameplayText.EliteSignalCaptured -> "Выберите реликвию"
    GameplayText.SelectMeldTarget -> "Выберите реликвию для усиления"
    GameplayText.SelectReplaceSlot -> "Выберите ячейку для замены"
    GameplayText.Reroll -> "Обновить · {0} · Q"
    GameplayText.SelectChoice -> "Выбрать вариант {0}: {1}"
    GameplayText.Select -> "Взять · {0}"
    GameplayText.ScrollableRewards -> "Прокручиваемое описание награды"
    GameplayText.PointTimer -> "{0} // {1}с"
    GameplayText.PointProgress -> "{0} // {1}% // {2}с"
    GameplayText.PerformanceTitle -> "ПРОИЗВОДИТЕЛЬНОСТЬ // F3 ВКЛ/СБРОС // СКОЛЬЗЯЩЕЕ ОКНО"
    GameplayText.PerformanceCompactTitle -> "ДИАГНОСТИКА // НАЖМИТЕ ДИАГН. // ОКНО"
    GameplayText.Frame -> "КАДР"
    GameplayText.Dispatch -> "ОБРАБОТКА"
    GameplayText.Canvas -> "ОТРИСОВКА"
    GameplayText.Rate -> "КАДР/С {0}  1% МИН {1}"
    GameplayText.Entities -> "ОБЪЕКТЫ ТЕК/ПИК"
    GameplayText.EnemyCounts -> "  ВРАГ {0}/{1}"
    GameplayText.ProjectileCounts -> "  СНР {0}/{1}"
    GameplayText.PickupCounts -> "  ПОДБ {0}/{1}"
    GameplayText.TrailCounts -> "  СЛЕД {0}/{1}"
    GameplayText.CompactFrame -> "КДР P50 {0}"
    GameplayText.Max -> " МАКС {0}"
    GameplayText.CompactSamples -> "N {0} О {1}"
    GameplayText.CompactPipeline -> " | ОБР P50 {0} P95 {1}"
    GameplayText.CompactDraw -> "РИС P50 {0} P95 {1}"
    GameplayText.CompactRate -> " | К/С {0} МИН {1}"
    GameplayText.CompactEnemies -> " | ВР {0}/{1}"
    GameplayText.CompactProjectiles -> " СНР {0}/{1}"
    GameplayText.CompactPickups -> "ПОДБ {0}/{1}"
    GameplayText.CompactTrail -> " СЛЕД {0}/{1}"
    GameplayText.Milliseconds -> "{0} мс"
    GameplayText.MaxRegular -> "  МАКС {0}"
    GameplayText.Samples -> "  N {0}  ОКНО {1}"
}
