// SPDX-FileCopyrightText: 2026 Vladislav Tomilov
// SPDX-License-Identifier: GPL-3.0-or-later

package kinetickk.flow.session.interaction.localization

internal fun russianSessionText(text: SessionText): String = when (text) {
    SessionText.UNKNOWN_CORE -> "Неизвестное ядро"
    SessionText.UNKNOWN_DISCOVERY -> "Неизвестная находка"
    SessionText.DISCOVERY_HELP -> "Найдите в забеге, чтобы открыть запись в коллекции."
    SessionText.UNLOCK_PROGRESS -> "Прогресс {0}/{1}"
    SessionText.COLLECTION_PROGRESS -> "Открыто {0} / {1}"
    SessionText.NEW_DISCOVERY -> "Новый!"

    SessionText.HOME_DESCRIPTION -> "Главная KINETICKK"
    SessionText.SELECTED_STATE -> "Выбрано"
    SessionText.AVAILABLE_STATE -> "Доступно"
    SessionText.LOCKED_STATE -> "Закрыто"
    SessionText.SELECT_CIRCLE -> "Выбрать ядро «Круг»"
    SessionText.SELECT_SQUARE -> "Выбрать ядро «Квадрат»"
    SessionText.SELECT_TRIANGLE -> "Выбрать ядро «Треугольник»"
    SessionText.SELECT_RING -> "Выбрать ядро «Кольцо»"
    SessionText.SELECT_DIAMOND -> "Выбрать ядро «Ромб»"
    SessionText.SELECT_TESSERACT -> "Выбрать ядро «Тессеракт»"
    SessionText.START_DESCRIPTION -> "Начать забег"
    SessionText.LAB_DESCRIPTION -> "Открыть кинетическую лабораторию"
    SessionText.ARMORY_DESCRIPTION -> "Открыть арсенал"
    SessionText.REBIRTH_DESCRIPTION -> "Открыть перерождение"
    SessionText.CODEX_DESCRIPTION -> "Открыть справочник"
    SessionText.SETTINGS_DESCRIPTION -> "Открыть настройки"
    SessionText.START_RUN -> "Играть"
    SessionText.REBIRTH_LEVEL -> "Перерождение {0}"
    SessionText.LAB -> "Улучшения"
    SessionText.ARMORY -> "Арсенал"
    SessionText.REBIRTH -> "Перерождение"
    SessionText.CODEX -> "Справочник"
    SessionText.SETTINGS -> "Настройки"
    SessionText.PROFILE_UNAVAILABLE -> "Профиль недоступен"
    SessionText.PROFILE_UNAVAILABLE_BODY -> "Не удалось безопасно прочитать локальный профиль. Локальные данные не изменены. Перезапустите приложение, чтобы повторить попытку."
    SessionText.STACK_LIMIT -> "Лимит копий"
    SessionText.NEXT_ACQUISITION -> "Может выпасть"
    SessionText.OFFER_LIMIT -> "Не выпадает"
    SessionText.OFFERS_FROM_LEVEL -> "Выпадает с"
    SessionText.OFFERS_FROM_LEVEL_HELP -> "Обычные предложения включают этот предмет, когда уровень забега или вся собранная материя достигает этого уровня."
    SessionText.OFFER_LIMIT_HELP -> "Обычные предложения пропускают предметы ниже их уровня и бесполезные: на лимите копий или на пределе эффекта."
    SessionText.STATUS -> "Статус"
    SessionText.PROGRESS -> "Прогресс"
    SessionText.RANK -> "Ранг"
    SessionText.UNLOCK_COST -> "Цена открытия"
    SessionText.WEAPON_LEVEL -> "Уровень"
    SessionText.WEAPON_LOCKED_HELP -> "Откройте его в арсенале за материю, чтобы начинать с ним забеги."
    SessionText.UNDISCOVERED -> "Не открыто"
    SessionText.START_WEAPON_SELECTED -> "Стартовое"
    SessionText.START_WEAPON_UNLOCKED -> "Открыто"
    SessionText.WEAPON_HELP -> "Можно получить в любом забеге. Каждый персонаж может использовать любое оружие."
    SessionText.WEAPON -> "Оружие"
    SessionText.LEVEL_SHORT -> "Ур. {0}"
    SessionText.MASTERY -> "Мастерство"
    SessionText.EQUIPPED -> "Экипировано"
    SessionText.RELIC_AVAILABLE -> "Не в сборке"
    SessionText.CHARACTER_LAB_HELP -> "Улучшения лаборатории действуют на всех персонажей."
    SessionText.CHARACTER -> "Персонаж"
    SessionText.UNLOCKED -> "Открыто"
    SessionText.LOCKED -> "Закрыто"
    SessionText.EMPTY_RELIC_SLOT -> "Пустая ячейка реликвии {0}"
    SessionText.EMPTY_RELIC_HELP -> "Получите реликвию в забеге, чтобы заполнить эту ячейку."
    SessionText.RELIC_SLOT -> "Ячейка реликвии"
    SessionText.EMPTY -> "Пусто"
    SessionText.SYNERGY_REQUIREMENT -> "Две разные реликвии аспекта «{0}». Дополнительные ранги не заменяют второй компонент."
    SessionText.REQUIRES -> "Требуется: {0}"
    SessionText.MISSING -> "Не хватает: {0}"
    SessionText.COMBINATION -> "Сочетание"
    SessionText.ACTIVE -> "Активно"
    SessionText.NO_RUN_INACTIVE -> "Нет забега"
    SessionText.INACTIVE -> "Неактивно"
    SessionText.ITEMS_TITLE -> "Предметы"
    SessionText.WEAPONS_TITLE -> "Оружие"
    SessionText.RELICS_TITLE -> "Реликвии"
    SessionText.FORMS_TITLE -> "Формы"
    SessionText.FILTER_ALL -> "Все"
    SessionText.FILTER_DISCOVERED -> "Открытые"
    SessionText.FILTER_BUILD -> "В сборке"
    SessionText.SEARCH_DESCRIPTION -> "Поиск в справочнике по названию"
    SessionText.ITEMS -> "Предметы"
    SessionText.CHARACTER_SOURCE -> "Персонаж"
    SessionText.LAB_SOURCE -> "Лаборатория / Перерождение"
    SessionText.SYNERGIES_SOURCE -> "Синергии"
    SessionText.MASTERY_SOURCE -> "Мастерство"
    SessionText.TEMPORARY_SOURCE -> "Временные эффекты"
    SessionText.SYNERGY_HELP -> "Две разные реликвии активируют синергию."
    SessionText.STACK_QUANTITY -> "Копии {0}"
    SessionText.NO_RUN -> "Нет забега"
    SessionText.NO_RUN_HELP -> "Начните забег, чтобы просмотреть персонажа, оружие и инвентарь. Полный каталог доступен всегда."
    SessionText.NO_MATCHES -> "Ничего не найдено"
    SessionText.NO_MATCHES_HELP -> "Попробуйте другое название или очистите поиск."
    SessionText.EMPTY_INVENTORY -> "Коллекция пуста"
    SessionText.EMPTY_INVENTORY_HELP -> "Находите предметы и реликвии в забегах — они останутся в коллекции."
    SessionText.TAB_BUILD -> "Сборка"
    SessionText.TAB_CATALOG -> "Коллекция"
    SessionText.TAB_SYNERGIES -> "Синергии"
}
