// SPDX-FileCopyrightText: 2026 Vladislav Tomilov
// SPDX-License-Identifier: GPL-3.0-or-later

package kinetickk.flow.session.interaction.localization

internal fun englishSessionText(text: SessionText): String = when (text) {
    SessionText.UNKNOWN_CORE -> "Unknown core"
    SessionText.UNKNOWN_DISCOVERY -> "Unknown discovery"
    SessionText.DISCOVERY_HELP -> "Find it during a run to reveal its collection entry."
    SessionText.UNLOCK_PROGRESS -> "Progress {0}/{1}"
    SessionText.COLLECTION_PROGRESS -> "Discovered {0} / {1}"
    SessionText.NEW_DISCOVERY -> "New!"

    SessionText.HOME_DESCRIPTION -> "KINETICKK home"
    SessionText.SELECTED_STATE -> "Selected"
    SessionText.AVAILABLE_STATE -> "Available"
    SessionText.LOCKED_STATE -> "Locked"
    SessionText.SELECT_CIRCLE -> "Select Circle core"
    SessionText.SELECT_SQUARE -> "Select Square core"
    SessionText.SELECT_TRIANGLE -> "Select Triangle core"
    SessionText.SELECT_RING -> "Select Ring core"
    SessionText.SELECT_DIAMOND -> "Select Diamond core"
    SessionText.SELECT_TESSERACT -> "Select Tesseract core"
    SessionText.START_DESCRIPTION -> "Start run"
    SessionText.LAB_DESCRIPTION -> "Open Kinetic Lab"
    SessionText.ARMORY_DESCRIPTION -> "Open Armory"
    SessionText.REBIRTH_DESCRIPTION -> "Open Rebirth"
    SessionText.CODEX_DESCRIPTION -> "Open Codex"
    SessionText.SETTINGS_DESCRIPTION -> "Open Settings"
    SessionText.START_RUN -> "Play"
    SessionText.REBIRTH_LEVEL -> "Rebirth {0}"
    SessionText.LAB -> "Upgrades"
    SessionText.ARMORY -> "Armory"
    SessionText.REBIRTH -> "Rebirth"
    SessionText.CODEX -> "Codex"
    SessionText.SETTINGS -> "Settings"
    SessionText.PROFILE_UNAVAILABLE -> "Profile unavailable"
    SessionText.PROFILE_UNAVAILABLE_BODY -> "The local profile could not be read safely. No local data was changed. Restart the application to try again."
    SessionText.STACK_LIMIT -> "STACK LIMIT"
    SessionText.NEXT_ACQUISITION -> "NEXT ACQUISITION POSSIBLE"
    SessionText.OFFER_LIMIT -> "ORDINARY OFFER LEVEL / EFFECT LIMIT"
    SessionText.OFFERS_FROM_LEVEL -> "ORDINARY OFFERS FROM LEVEL {0}"
    SessionText.DISCOVERED -> "DISCOVERED"
    SessionText.UNDISCOVERED -> "UNDISCOVERED"
    SessionText.START_WEAPON_SELECTED -> "STARTING WEAPON SELECTED"
    SessionText.START_WEAPON_UNLOCKED -> "STARTING WEAPON UNLOCKED"
    SessionText.START_WEAPON_LOCKED -> "STARTING WEAPON LOCKED\n{0} Matter in Armory"
    SessionText.WEAPON_HELP -> "Available as an acquisition during any run. Every character can use every weapon."
    SessionText.WEAPON -> "Weapon"
    SessionText.LEVEL_SHORT -> "Lvl {0}"
    SessionText.EQUIPPED_MASTERY -> "EQUIPPED\n{0} mastery"
    SessionText.EQUIPPED -> "EQUIPPED"
    SessionText.RELIC_AVAILABLE -> "NOT IN BUILD\nAVAILABLE DURING RUNS"
    SessionText.CHARACTER_LAB_HELP -> "All characters share Lab upgrades."
    SessionText.CHARACTER -> "Character"
    SessionText.UNLOCKED -> "UNLOCKED"
    SessionText.LOCKED -> "LOCKED"
    SessionText.EMPTY_RELIC_SLOT -> "Empty relic slot {0}"
    SessionText.EMPTY_RELIC_HELP -> "Acquire a relic during a run to fill this slot."
    SessionText.RELIC_SLOT -> "Relic slot"
    SessionText.EMPTY -> "EMPTY"
    SessionText.SYNERGY_REQUIREMENT -> "Two different {0} relics. Extra ranks do not replace the second component."
    SessionText.REQUIRES -> "Requires: {0}"
    SessionText.MISSING -> "Missing: {0}"
    SessionText.COMBINATION -> "Combination"
    SessionText.ACTIVE -> "ACTIVE"
    SessionText.NO_RUN_INACTIVE -> "INACTIVE, NO RUN"
    SessionText.INACTIVE -> "INACTIVE"
    SessionText.ITEMS_TITLE -> "Items"
    SessionText.WEAPONS_TITLE -> "Weapons"
    SessionText.RELICS_TITLE -> "Relics"
    SessionText.FORMS_TITLE -> "Forms"
    SessionText.FILTER_ALL -> "All"
    SessionText.FILTER_DISCOVERED -> "Discovered"
    SessionText.FILTER_BUILD -> "In build"
    SessionText.SEARCH_DESCRIPTION -> "Search catalog by name"
    SessionText.ITEMS -> "Items"
    SessionText.CHARACTER_SOURCE -> "Character"
    SessionText.LAB_SOURCE -> "Lab / Rebirth"
    SessionText.SYNERGIES_SOURCE -> "Synergies"
    SessionText.MASTERY_SOURCE -> "Mastery"
    SessionText.TEMPORARY_SOURCE -> "Temporary"
    SessionText.SYNERGY_HELP -> "Two different relics activate a synergy."
    SessionText.RANK_QUANTITY -> "Rank {0}"
    SessionText.STACK_QUANTITY -> "Stack {0}"
    SessionText.NO_RUN -> "No run"
    SessionText.NO_RUN_HELP -> "Begin a run to inspect your character, weapon and inventory. The full catalog remains available."
    SessionText.NO_MATCHES -> "No matches"
    SessionText.NO_MATCHES_HELP -> "Try another name or clear the search."
    SessionText.EMPTY_INVENTORY -> "Collection empty"
    SessionText.EMPTY_INVENTORY_HELP -> "Find items and relics during runs to keep them in your collection."
    SessionText.TAB_BUILD -> "Build"
    SessionText.TAB_CATALOG -> "Collection"
    SessionText.TAB_SYNERGIES -> "Synergies"
}
