// SPDX-FileCopyrightText: 2026 Vladislav Tomilov
// SPDX-License-Identifier: GPL-3.0-or-later

package kinetickk.flow.session.interaction.localization

internal fun russianSessionText(text: SessionText): String = when (text) {
    SessionText.HOME_DESCRIPTION -> "Главная KINETICKK"
    SessionText.SELECTED_STATE -> "Выбрано"
    SessionText.AVAILABLE_STATE -> "Доступно"
    SessionText.LOCKED_STATE -> "Закрыто"
    SessionText.SELECT_CIRCLE -> "Выбрать ядро «Круг»"
    SessionText.SELECT_SQUARE -> "Выбрать ядро «Квадрат»"
    SessionText.SELECT_TRIANGLE -> "Выбрать ядро «Треугольник»"
    SessionText.SELECT_RING -> "Выбрать ядро «Кольцо»"
    SessionText.SELECT_DIAMOND -> "Выбрать ядро «Ромб»"
    SessionText.SELECT_TESSERACT -> "Выбрать ядро «Тессеракт»"
    SessionText.START_DESCRIPTION -> "Начать забег"
    SessionText.LAB_DESCRIPTION -> "Открыть кинетическую лабораторию"
    SessionText.ARMORY_DESCRIPTION -> "Открыть арсенал"
    SessionText.REBIRTH_DESCRIPTION -> "Открыть перерождение"
    SessionText.CODEX_DESCRIPTION -> "Открыть справочник"
    SessionText.SETTINGS_DESCRIPTION -> "Открыть настройки"
    SessionText.NAV_LAB -> "ЛАБОРАТОРИЯ [L]"
    SessionText.NAV_ARMORY -> "АРСЕНАЛ [A]"
    SessionText.NAV_REBIRTH -> "ПЕРЕРОЖДЕНИЕ [B]"
    SessionText.NAV_CODEX -> "СПРАВОЧНИК [C]"
    SessionText.NAV_SETTINGS -> "НАСТРОЙКИ [S]"
    SessionText.HOME_SLOGAN -> "ДВИЖЕНИЕ — ВАШЕ ОРУЖИЕ. КУРСОР — ВАША УГРОЗА."
    SessionText.HOME_INSTRUCTIONS -> "ВЕДИТЕ ЯДРО  //  НАБИРАЙТЕ ИМПУЛЬС  //  ИЗБЕГАЙТЕ СИНГУЛЯРНОСТИ"
    SessionText.SELECT_CORE -> "ВЫБЕРИТЕ ЯДРО"
    SessionText.START_RUN -> "НАЧАТЬ ЗАБЕГ"
    SessionText.CLICK_TAP_ENTER -> "КЛИК / КАСАНИЕ / ENTER"
    SessionText.MATTER_REBIRTH -> "КИНЕТИЧЕСКАЯ МАТЕРИЯ {0} // ПЕРЕРОЖДЕНИЕ {1}"
    SessionText.COLLECTION_COUNTS -> "ОТКРЫТО {0}/{1}  //  ОРУЖИЕ {2}/{3}"
    SessionText.DIRECTIVE -> "ДИРЕКТИВА {0}"
    SessionText.COPYRIGHT -> "KINETICKK 0.2.0 // АВТОРСКОЕ ПРАВО (C) 2026 ВЛАДИСЛАВ ТОМИЛОВ // GNU GPL V3+"
    SessionText.LICENSE_NOTICE -> "РАСПРОСТРАНЕНИЕ ПО GPL V3+ // БЕЗ ГАРАНТИЙ"
    SessionText.SOURCE_LICENSE -> "КОД И ЛИЦЕНЗИЯ: GITHUB.COM/4WL2D/KINETICKK"
    SessionText.COMPACT_SLOGAN -> "ДВИГАЙТЕ СИНГУЛЯРНОСТЬ. НАБИРАЙТЕ ИМПУЛЬС."
    SessionText.MATTER -> "МАТЕРИЯ {0}"
    SessionText.REBIRTH_LEVEL -> "ПЕРЕРОЖДЕНИЕ {0}"
    SessionText.TOUCH_SLOGAN -> "ВАШЕ КАСАНИЕ — УГРОЗА"
    SessionText.COMPACT_INSTRUCTIONS -> "ВЕДИТЕ ЯДРО // НАБИРАЙТЕ ИМПУЛЬС"
    SessionText.COMPACT_MATTER_REBIRTH -> "МАТЕРИЯ {0} // ПЕРЕРОЖДЕНИЕ {1}"
    SessionText.LAB -> "ЛАБОРАТОРИЯ"
    SessionText.ARMORY -> "АРСЕНАЛ"
    SessionText.REBIRTH -> "ПЕРЕРОЖДЕНИЕ"
    SessionText.CODEX -> "СПРАВОЧНИК"
    SessionText.SETTINGS -> "НАСТРОЙКИ"
    SessionText.SELECTED -> "ВЫБРАНО"
    SessionText.SELECT -> "ВЫБРАТЬ"
    SessionText.TAP_ENTER -> "КОСНИТЕСЬ ДЛЯ ВХОДА"
    SessionText.AVAILABLE -> "ДОСТУПНО"
    SessionText.ELITES_TARGET -> "ЭЛИТНЫХ: {0}"
    SessionText.DASH_TARGET -> "ПОПАДАНИЙ РЫВКОМ: {0}"
    SessionText.ORBIT_CLEAR -> "ПРОЙДИТЕ ОРБИТУ"
    SessionText.ARCHITECT_WIN -> "ПОБЕДИТЕ АРХИТЕКТОРА"
    SessionText.FORMS_TARGET -> "ПОБЕДЫ ЗА ФОРМЫ: {0}"
    SessionText.PROFILE_UNAVAILABLE -> "ПРОФИЛЬ НЕДОСТУПЕН"
    SessionText.PROFILE_UNAVAILABLE_BODY -> "НЕ УДАЛОСЬ БЕЗОПАСНО ПРОЧИТАТЬ ЛОКАЛЬНЫЙ ПРОФИЛЬ. ЛОКАЛЬНЫЕ ДАННЫЕ НЕ ИЗМЕНЕНЫ. ПЕРЕЗАПУСТИТЕ ПРИЛОЖЕНИЕ, ЧТОБЫ ПОВТОРИТЬ ПОПЫТКУ."
    SessionText.STACK_LIMIT -> "ЛИМИТ КОПИЙ"
    SessionText.NEXT_ACQUISITION -> "МОЖНО ПОЛУЧИТЬ ЕЩЁ"
    SessionText.OFFER_LIMIT -> "ОГРАНИЧЕНИЕ УРОВНЯ / ЭФФЕКТА ДЛЯ ПРЕДЛОЖЕНИЙ"
    SessionText.OFFERS_FROM_LEVEL -> "ОБЫЧНЫЕ ПРЕДЛОЖЕНИЯ С УРОВНЯ {0}"
    SessionText.DISCOVERED -> "ОТКРЫТО"
    SessionText.UNDISCOVERED -> "НЕ ОТКРЫТО"
    SessionText.START_WEAPON_SELECTED -> "НАЧАЛЬНОЕ ОРУЖИЕ ВЫБРАНО"
    SessionText.START_WEAPON_UNLOCKED -> "НАЧАЛЬНОЕ ОРУЖИЕ ОТКРЫТО"
    SessionText.START_WEAPON_LOCKED -> "НАЧАЛЬНОЕ ОРУЖИЕ ЗАКРЫТО · {0} материи в арсенале"
    SessionText.WEAPON_HELP -> "Можно получить в любом забеге. Каждый персонаж может использовать любое оружие."
    SessionText.WEAPON -> "ОРУЖИЕ"
    SessionText.LEVEL_SHORT -> "УР. {0}"
    SessionText.EQUIPPED_MASTERY -> "ЭКИПИРОВАНО · мастерство: {0}"
    SessionText.EQUIPPED -> "ЭКИПИРОВАНО"
    SessionText.RELIC_AVAILABLE -> "НЕ В СБОРКЕ · ДОСТУПНО В ЗАБЕГАХ"
    SessionText.CHARACTER_LAB_HELP -> "Улучшения лаборатории действуют на всех персонажей."
    SessionText.CHARACTER -> "ПЕРСОНАЖ"
    SessionText.UNLOCKED -> "ОТКРЫТО"
    SessionText.LOCKED -> "ЗАКРЫТО"
    SessionText.EMPTY_RELIC_SLOT -> "Пустая ячейка реликвии {0}"
    SessionText.EMPTY_RELIC_HELP -> "Получите реликвию в забеге, чтобы заполнить эту ячейку."
    SessionText.RELIC_SLOT -> "ЯЧЕЙКА РЕЛИКВИИ"
    SessionText.EMPTY -> "ПУСТО"
    SessionText.SYNERGY_REQUIREMENT -> "Две разные реликвии аспекта «{0}». Дополнительные ранги не заменяют второй компонент."
    SessionText.REQUIRES -> "Требуется: {0}"
    SessionText.MISSING -> "Не хватает: {0}"
    SessionText.COMBINATION -> "СОЧЕТАНИЕ"
    SessionText.ACTIVE -> "АКТИВНО"
    SessionText.NO_RUN_INACTIVE -> "НЕТ ЗАБЕГА · НЕАКТИВНО"
    SessionText.INACTIVE -> "НЕАКТИВНО"
    SessionText.CLOSE -> "ЗАКРЫТЬ · Esc"
    SessionText.ITEMS_TITLE -> "Предметы"
    SessionText.WEAPONS_TITLE -> "Оружие"
    SessionText.RELICS_TITLE -> "Реликвии"
    SessionText.FORMS_TITLE -> "Формы"
    SessionText.FILTER_ALL -> "Все"
    SessionText.FILTER_DISCOVERED -> "Открытые"
    SessionText.FILTER_BUILD -> "В сборке"
    SessionText.SEARCH_DESCRIPTION -> "Поиск в справочнике по названию"
    SessionText.SEARCH_PLACEHOLDER -> "Поиск по названию…"
    SessionText.WEAPON_LEVEL -> "ОРУЖИЕ · УРОВЕНЬ {0}"
    SessionText.RELIC_COUNT -> "РЕЛИКВИИ · {0}/{1}"
    SessionText.ITEMS -> "ПРЕДМЕТЫ"
    SessionText.EFFECTIVE_STATS -> "{0} ИТОГОВЫЕ ХАРАКТЕРИСТИКИ"
    SessionText.CHARACTER_SOURCE -> "Персонаж"
    SessionText.LAB_SOURCE -> "Лаборатория / Перерождение"
    SessionText.ITEMS_SOURCE -> "Предметы"
    SessionText.RELICS_SOURCE -> "Реликвии"
    SessionText.SYNERGIES_SOURCE -> "Синергии"
    SessionText.MASTERY_SOURCE -> "Мастерство"
    SessionText.TEMPORARY_SOURCE -> "Временные эффекты"
    SessionText.SYNERGY_HELP -> "Два разных компонента активируют резонанс. Реликвии Владычества сохраняют свою особую роль."
    SessionText.SELECT_SLOT -> "ВЫБЕРИТЕ ЯЧЕЙКУ"
    SessionText.SELECT_SLOT_HELP -> "Наведите курсор или переведите фокус для просмотра. Нажмите на ячейку или Enter, чтобы закрепить описание."
    SessionText.RANK_QUANTITY -> "РАНГ {0}"
    SessionText.STACK_QUANTITY -> "КОПИИ {0}"
    SessionText.NO_RUN -> "НЕТ ЗАБЕГА"
    SessionText.NO_RUN_HELP -> "Начните забег, чтобы просмотреть персонажа, оружие и инвентарь. Полный каталог доступен всегда."
    SessionText.NO_MATCHES -> "НИЧЕГО НЕ НАЙДЕНО"
    SessionText.NO_MATCHES_HELP -> "Попробуйте другое название или очистите поиск."
    SessionText.EMPTY_INVENTORY -> "ИНВЕНТАРЬ ПУСТ"
    SessionText.EMPTY_INVENTORY_HELP -> "Пока нет предметов в инвентаре или подходящих под фильтр."
    SessionText.TAB_BUILD -> "Сборка"
    SessionText.TAB_CATALOG -> "Каталог"
    SessionText.TAB_SYNERGIES -> "Синергии"
    SessionText.COMPACT_LICENSE -> "GPLV3+ // КОД: GITHUB.COM/4WL2D/KINETICKK"
}
