// SPDX-FileCopyrightText: 2026 Vladislav Tomilov
// SPDX-License-Identifier: GPL-3.0-or-later

package kinetickk.flow.session.interaction.localization

internal fun englishSessionText(text: SessionText): String = when (text) {
    SessionText.HOME_DESCRIPTION -> "KINETICKK home"
    SessionText.SELECTED_STATE -> "Selected"
    SessionText.AVAILABLE_STATE -> "Available"
    SessionText.LOCKED_STATE -> "Locked"
    SessionText.SELECT_CIRCLE -> "Select Circle core"
    SessionText.SELECT_SQUARE -> "Select Square core"
    SessionText.SELECT_TRIANGLE -> "Select Triangle core"
    SessionText.SELECT_RING -> "Select Ring core"
    SessionText.SELECT_DIAMOND -> "Select Diamond core"
    SessionText.SELECT_TESSERACT -> "Select Tesseract core"
    SessionText.START_DESCRIPTION -> "Start run"
    SessionText.LAB_DESCRIPTION -> "Open Kinetic Lab"
    SessionText.ARMORY_DESCRIPTION -> "Open Armory"
    SessionText.REBIRTH_DESCRIPTION -> "Open Rebirth"
    SessionText.CODEX_DESCRIPTION -> "Open Codex"
    SessionText.SETTINGS_DESCRIPTION -> "Open Settings"
    SessionText.NAV_LAB -> "LAB [L]"
    SessionText.NAV_ARMORY -> "ARMORY [A]"
    SessionText.NAV_REBIRTH -> "REBIRTH [B]"
    SessionText.NAV_CODEX -> "CODEX [C]"
    SessionText.NAV_SETTINGS -> "SETTINGS [S]"
    SessionText.HOME_SLOGAN -> "YOUR MOVEMENT IS THE WEAPON. YOUR CURSOR IS THE THREAT."
    SessionText.HOME_INSTRUCTIONS -> "Move the pointer · Space to dash · Shift to brake"
    SessionText.SELECT_CORE -> "SELECT CORE"
    SessionText.START_RUN -> "Play"
    SessionText.CLICK_TAP_ENTER -> "CLICK / TAP / ENTER"
    SessionText.MATTER_REBIRTH -> "KINETIC MATTER {0} // REBIRTH {1}"
    SessionText.COLLECTION_COUNTS -> "DISCOVERED {0}/{1}  //  WEAPONS {2}/{3}"
    SessionText.DIRECTIVE -> "DIRECTIVE {0}"
    SessionText.COPYRIGHT -> "KINETICKK 0.2.0 · © 2026 Vladislav Tomilov · GPL v3+"
    SessionText.LICENSE_NOTICE -> "No warranty · github.com/4wl2d/KINETICKK"
    SessionText.SOURCE_LICENSE -> "SOURCE + LICENSE: GITHUB.COM/4WL2D/KINETICKK"
    SessionText.COMPACT_SLOGAN -> "MOVE THE SINGULARITY. BUILD MOMENTUM."
    SessionText.MATTER -> "Matter {0}"
    SessionText.REBIRTH_LEVEL -> "REBIRTH {0}"
    SessionText.TOUCH_SLOGAN -> "YOUR TOUCH IS THE THREAT"
    SessionText.COMPACT_INSTRUCTIONS -> "Guide the core along an arc"
    SessionText.COMPACT_MATTER_REBIRTH -> "MATTER {0} // REBIRTH {1}"
    SessionText.LAB -> "Upgrades"
    SessionText.ARMORY -> "Armory"
    SessionText.REBIRTH -> "Rebirth"
    SessionText.CODEX -> "Codex"
    SessionText.SETTINGS -> "Settings"
    SessionText.SELECTED -> "SELECTED"
    SessionText.SELECT -> "SELECT"
    SessionText.TAP_ENTER -> "TAP TO ENTER"
    SessionText.AVAILABLE -> "AVAILABLE"
    SessionText.ELITES_TARGET -> "{0} ELITES"
    SessionText.DASH_TARGET -> "{0} DASH HITS"
    SessionText.ORBIT_CLEAR -> "ORBIT CLEAR"
    SessionText.ARCHITECT_WIN -> "ARCHITECT WIN"
    SessionText.FORMS_TARGET -> "{0} FORMS WON"
    SessionText.PROFILE_UNAVAILABLE -> "PROFILE UNAVAILABLE"
    SessionText.PROFILE_UNAVAILABLE_BODY -> "THE LOCAL PROFILE COULD NOT BE READ SAFELY. NO LOCAL DATA WAS CHANGED. RESTART THE APPLICATION TO TRY AGAIN."
    SessionText.STACK_LIMIT -> "STACK LIMIT"
    SessionText.NEXT_ACQUISITION -> "NEXT ACQUISITION POSSIBLE"
    SessionText.OFFER_LIMIT -> "ORDINARY OFFER LEVEL / EFFECT LIMIT"
    SessionText.OFFERS_FROM_LEVEL -> "ORDINARY OFFERS FROM LEVEL {0}"
    SessionText.DISCOVERED -> "DISCOVERED"
    SessionText.UNDISCOVERED -> "UNDISCOVERED"
    SessionText.START_WEAPON_SELECTED -> "STARTING WEAPON SELECTED"
    SessionText.START_WEAPON_UNLOCKED -> "STARTING WEAPON UNLOCKED"
    SessionText.START_WEAPON_LOCKED -> "STARTING WEAPON LOCKED · {0} Matter in Armory"
    SessionText.WEAPON_HELP -> "Available as an acquisition during any run. Every character can use every weapon."
    SessionText.WEAPON -> "WEAPON"
    SessionText.LEVEL_SHORT -> "LV {0}"
    SessionText.EQUIPPED_MASTERY -> "EQUIPPED · {0} mastery"
    SessionText.EQUIPPED -> "EQUIPPED"
    SessionText.RELIC_AVAILABLE -> "NOT IN BUILD · AVAILABLE DURING RUNS"
    SessionText.CHARACTER_LAB_HELP -> "All characters share Lab upgrades."
    SessionText.CHARACTER -> "CHARACTER"
    SessionText.UNLOCKED -> "UNLOCKED"
    SessionText.LOCKED -> "LOCKED"
    SessionText.EMPTY_RELIC_SLOT -> "Empty relic slot {0}"
    SessionText.EMPTY_RELIC_HELP -> "Acquire a relic during a run to fill this slot."
    SessionText.RELIC_SLOT -> "RELIC SLOT"
    SessionText.EMPTY -> "EMPTY"
    SessionText.SYNERGY_REQUIREMENT -> "Two different {0} relics. Extra ranks do not replace the second component."
    SessionText.REQUIRES -> "Requires: {0}"
    SessionText.MISSING -> "Missing: {0}"
    SessionText.COMBINATION -> "COMBINATION"
    SessionText.ACTIVE -> "ACTIVE"
    SessionText.NO_RUN_INACTIVE -> "NO RUN · INACTIVE"
    SessionText.INACTIVE -> "INACTIVE"
    SessionText.CLOSE -> "Close · Esc"
    SessionText.ITEMS_TITLE -> "Items"
    SessionText.WEAPONS_TITLE -> "Weapons"
    SessionText.RELICS_TITLE -> "Relics"
    SessionText.FORMS_TITLE -> "Forms"
    SessionText.FILTER_ALL -> "All"
    SessionText.FILTER_DISCOVERED -> "Discovered"
    SessionText.FILTER_BUILD -> "In build"
    SessionText.SEARCH_DESCRIPTION -> "Search catalog by name"
    SessionText.SEARCH_PLACEHOLDER -> "Search by name…"
    SessionText.WEAPON_LEVEL -> "WEAPON · LEVEL {0}"
    SessionText.RELIC_COUNT -> "RELICS · {0}/{1}"
    SessionText.ITEMS -> "ITEMS"
    SessionText.EFFECTIVE_STATS -> "{0} Stats"
    SessionText.CHARACTER_SOURCE -> "Character"
    SessionText.LAB_SOURCE -> "Lab / Rebirth"
    SessionText.ITEMS_SOURCE -> "Items"
    SessionText.RELICS_SOURCE -> "Relics"
    SessionText.SYNERGIES_SOURCE -> "Synergies"
    SessionText.MASTERY_SOURCE -> "Mastery"
    SessionText.TEMPORARY_SOURCE -> "Temporary"
    SessionText.SYNERGY_HELP -> "Two different relics activate a synergy."
    SessionText.SELECT_SLOT -> "Select an item"
    SessionText.SELECT_SLOT_HELP -> "Hover to preview. Click to pin."
    SessionText.RANK_QUANTITY -> "RANK {0}"
    SessionText.STACK_QUANTITY -> "STACK {0}"
    SessionText.NO_RUN -> "NO RUN"
    SessionText.NO_RUN_HELP -> "Begin a run to inspect your character, weapon and inventory. The full catalog remains available."
    SessionText.NO_MATCHES -> "NO MATCHES"
    SessionText.NO_MATCHES_HELP -> "Try another name or clear the search."
    SessionText.EMPTY_INVENTORY -> "EMPTY INVENTORY"
    SessionText.EMPTY_INVENTORY_HELP -> "No items match this inventory or filter yet."
    SessionText.TAB_BUILD -> "Build"
    SessionText.TAB_CATALOG -> "Catalog"
    SessionText.TAB_SYNERGIES -> "Synergies"
    SessionText.COMPACT_LICENSE -> "GPLV3+ // SOURCE: GITHUB.COM/4WL2D/KINETICKK"
}
