// SPDX-FileCopyrightText: 2026 Vladislav Tomilov
// SPDX-License-Identifier: GPL-3.0-or-later

package kinetickk.flow.session.interaction.localization

internal fun englishSessionText(text: SessionText): String = when (text) {
    SessionText.UNKNOWN_CORE -> "Unknown core"
    SessionText.UNKNOWN_DISCOVERY -> "Unknown discovery"
    SessionText.DISCOVERY_HELP -> "Find it during a run to reveal its collection entry."
    SessionText.UNLOCK_PROGRESS -> "Progress {0}/{1}"
    SessionText.COLLECTION_PROGRESS -> "Discovered {0} / {1}"
    SessionText.NEW_DISCOVERY -> "New!"

    SessionText.HOME_DESCRIPTION -> "KINETICKK home"
    SessionText.SELECTED_STATE -> "Selected"
    SessionText.AVAILABLE_STATE -> "Available"
    SessionText.LOCKED_STATE -> "Locked"
    SessionText.SELECT_CIRCLE -> "Select Circle core"
    SessionText.SELECT_SQUARE -> "Select Square core"
    SessionText.SELECT_TRIANGLE -> "Select Triangle core"
    SessionText.SELECT_RING -> "Select Ring core"
    SessionText.SELECT_DIAMOND -> "Select Diamond core"
    SessionText.SELECT_TESSERACT -> "Select Tesseract core"
    SessionText.START_DESCRIPTION -> "Start run"
    SessionText.LAB_DESCRIPTION -> "Open Kinetic Lab"
    SessionText.ARMORY_DESCRIPTION -> "Open Armory"
    SessionText.REBIRTH_DESCRIPTION -> "Open Rebirth"
    SessionText.CODEX_DESCRIPTION -> "Open Codex"
    SessionText.SETTINGS_DESCRIPTION -> "Open Settings"
    SessionText.START_RUN -> "Play"
    SessionText.REBIRTH_LEVEL -> "Rebirth {0}"
    SessionText.LAB -> "Upgrades"
    SessionText.ARMORY -> "Armory"
    SessionText.REBIRTH -> "Rebirth"
    SessionText.CODEX -> "Codex"
    SessionText.SETTINGS -> "Settings"
    SessionText.PROFILE_UNAVAILABLE -> "Profile unavailable"
    SessionText.PROFILE_UNAVAILABLE_BODY -> "The local profile could not be read safely. No local data was changed. Restart the application to try again."
    SessionText.STACK_LIMIT -> "Stack limit"
    SessionText.NEXT_ACQUISITION -> "Can be offered"
    SessionText.OFFER_LIMIT -> "Not offered"
    SessionText.OFFERS_FROM_LEVEL -> "Offered from"
    SessionText.OFFERS_FROM_LEVEL_HELP -> "An item joins ordinary offers once your run level reaches the item's level, or once the Matter you have collected in all runs unlocks that level: one level per 40 Matter, up to Lvl 80. The level shown already counts your Matter."
    SessionText.OFFER_LIMIT_HELP -> "Ordinary offers skip items whose level is not reached yet and items that would add nothing: at the stack limit or at an effect cap."
    SessionText.STATUS -> "Status"
    SessionText.PROGRESS -> "Progress"
    SessionText.RANK -> "Rank"
    SessionText.UNLOCK_COST -> "Unlock cost"
    SessionText.WEAPON_LEVEL -> "Level"
    SessionText.WEAPON_LOCKED_HELP -> "Unlock it in the Armory with Matter to start runs with it."
    SessionText.UNDISCOVERED -> "Undiscovered"
    SessionText.START_WEAPON_SELECTED -> "Starting weapon"
    SessionText.START_WEAPON_UNLOCKED -> "Unlocked"
    SessionText.WEAPON_HELP -> "Available as an acquisition during any run. Every character can use every weapon."
    SessionText.WEAPON -> "Weapon"
    SessionText.LEVEL_SHORT -> "Lvl {0}"
    SessionText.MASTERY -> "Mastery"
    SessionText.EQUIPPED -> "Equipped"
    SessionText.RELIC_AVAILABLE -> "Not in build"
    SessionText.CHARACTER_LAB_HELP -> "All characters share Lab upgrades."
    SessionText.CHARACTER -> "Character"
    SessionText.UNLOCKED -> "Unlocked"
    SessionText.LOCKED -> "Locked"
    SessionText.EMPTY_RELIC_SLOT -> "Empty relic slot"
    SessionText.EMPTY_RELIC_HELP -> "Acquire a relic during a run to fill this slot."
    SessionText.RELIC_SLOT -> "Relic slot"
    SessionText.EMPTY -> "Empty"
    SessionText.SYNERGY_REQUIREMENT -> "Two different {0} relics activate this synergy. Extra ranks of one relic do not replace the second relic."
    SessionText.SYNERGY_ASPECT_PAIR -> "2 × {0}"
    SessionText.REQUIRES -> "Requires"
    SessionText.MISSING -> "Missing"
    SessionText.COMBINATION -> "Combination"
    SessionText.ACTIVE -> "Active"
    SessionText.NO_RUN_INACTIVE -> "No run"
    SessionText.INACTIVE -> "Inactive"
    SessionText.ITEMS_TITLE -> "Items"
    SessionText.WEAPONS_TITLE -> "Weapons"
    SessionText.RELICS_TITLE -> "Relics"
    SessionText.FORMS_TITLE -> "Forms"
    SessionText.FILTER_ALL -> "All"
    SessionText.FILTER_DISCOVERED -> "Discovered"
    SessionText.FILTER_BUILD -> "In build"
    SessionText.SEARCH_DESCRIPTION -> "Search catalog by name"
    SessionText.ITEMS -> "Items"
    SessionText.CHARACTER_SOURCE -> "Character"
    SessionText.LAB_SOURCE -> "Lab / Rebirth"
    SessionText.SYNERGIES_SOURCE -> "Synergies"
    SessionText.MASTERY_SOURCE -> "Mastery"
    SessionText.TEMPORARY_SOURCE -> "Temporary"
    SessionText.SYNERGY_HELP -> "Two different relics activate a synergy."
    SessionText.STACK_QUANTITY -> "Stack {0}"
    SessionText.NO_RUN -> "No run"
    SessionText.NO_RUN_HELP -> "Begin a run to inspect your character, weapon and inventory. The full catalog remains available."
    SessionText.NO_MATCHES -> "No matches"
    SessionText.NO_MATCHES_HELP -> "Try another name or clear the search."
    SessionText.EMPTY_INVENTORY -> "Collection empty"
    SessionText.EMPTY_INVENTORY_HELP -> "Find items and relics during runs to keep them in your collection."
    SessionText.TAB_BUILD -> "Build"
    SessionText.TAB_CATALOG -> "Collection"
    SessionText.TAB_SYNERGIES -> "Synergies"
}
