// SPDX-FileCopyrightText: 2026 Vladislav Tomilov
// SPDX-License-Identifier: GPL-3.0-or-later

package kinetickk.ball.content.api

internal val ContentPhrasesInRussian: Map<String, String> = mapOf(
    "Drifter" to "Дрейфер",
    "Shooter" to "Стрелок",
    "Charger" to "Таранщик",
    "Interceptor" to "Перехватчик",
    "Weaver" to "Ткач",
    "Warden" to "Страж",
    "Splitter" to "Делитель",
    "Elite" to "Элитный враг",
    "Architect" to "Архитектор",
    "Transcendent" to "Запредельная скорость",
    "Impact damage" to "Урон от столкновений",
    "Weapon power" to "Мощность оружия",
    "Mass" to "Масса",
    "Magnetism" to "Магнетизм",
    "Cooling" to "Охлаждение",
    "Maximum integrity" to "Максимальная прочность",
    "Integrity regeneration" to "Восстановление прочности",
    "Dash power" to "Сила рывка",
    "Dash efficiency" to "Эффективность рывка",
    "Critical chance" to "Шанс критического удара",
    "Critical damage" to "Критический урон",
    "Pickup radius" to "Радиус сбора",
    "Luck" to "Удача",
    "Data gain" to "Получение данных",
    "Matter gain" to "Получение материи",
    "Attack speed" to "Скорость атаки",
    "Shield capacity" to "Ёмкость щита",
    "Damage reduction" to "Снижение урона",
    "Combo window" to "Окно комбо",
    "Overdrive gain" to "Накопление перегрузки",
    "Common" to "Обычный",
    "Uncommon" to "Необычный",
    "Rare" to "Редкий",
    "Epic" to "Эпический",
    "Legendary" to "Легендарный",
    "Calibrated" to "Откалибровано",
    "Amplified" to "Усилено",
    "Resonant" to "Резонирует",
    "Ascended" to "Вознесено",
    "Circle" to "Круг",
    "Square" to "Квадрат",
    "Triangle" to "Треугольник",
    "Ring" to "Кольцо",
    "Diamond" to "Ромб",
    "Tesseract" to "Тессеракт",
    "ORB" to "КРУГ",
    "SHARD" to "ТРЕУГОЛЬНИК",
    "Vector" to "Вектор",
    "Gravitic" to "Гравитация",
    "Ion" to "Ион",
    "Rift" to "Разлом",
    "Prism" to "Призма",
    "Entropy" to "Энтропия",
    "Sovereign" to "Владычество",
    "Baseline" to "Исходная",
    "Swarm" to "Рой",
    "Fortified" to "Укрепление",
    "Overclocked" to "Разгон",
    "The original Architect cycle." to "Исходный цикл Архитектора.",
    "This cycle adds another rank of hostile density." to "Этот цикл повышает плотность врагов ещё на один ранг.",
    "This cycle adds another rank of enemy integrity." to "Этот цикл повышает прочность врагов ещё на один ранг.",
    "This cycle adds another rank of hostile speed and damage." to "Этот цикл повышает скорость и урон врагов ещё на один ранг.",
    "Follow a real arc to charge a circular wave released by the next primary hit." to "Двигайтесь по дуге, чтобы зарядить круговую волну, которую выпустит следующее основное попадание.",
    "Brake from speed to build a temporary barrier. Dash spends its charge on a ram." to "Тормозите на скорости, чтобы создать временный барьер. Рывок расходует его заряд на таран.",
    "Dash through enemies to mark them briefly; a subsequent hit opens each mark." to "Пронзайте врагов рывком, чтобы ненадолго пометить их. Следующее попадание раскрывает каждую метку.",
    "Movement expands a damaging ring. Brake contracts it, preserving a safe inner dead zone." to "Движение расширяет поражающее кольцо. Торможение сжимает его, сохраняя безопасную зону внутри.",
    "The opening of Brake can parry an approaching threat and release a counterattack." to "Начало торможения позволяет парировать приближающуюся угрозу и провести контратаку.",
    "Separated real Dash positions build a bounded lattice. Closing it or Brake collapses it." to "Рывки из разных точек создают ограниченную решётку. Замыкание контура или торможение схлопывает её.",
    "Available from the start" to "Доступен с самого начала",
    "Defeat 3 elites across runs" to "Победите 3 элитных врагов за все забеги",
    "Land 20 Dash hits across runs" to "Нанесите 20 попаданий рывком за все забеги",
    "Complete a Collapsing Orbit" to "Завершите испытание «Схлопывающаяся орбита»",
    "Defeat the Architect" to "Победите Архитектора",
    "Win with 3 different characters" to "Победите за 3 разных персонажей",
    "Flux Wake" to "Потоковый след",
    "Morningstar" to "Моргенштерн",
    "Phase Lattice" to "Фазовая решётка",
    "Null Lance" to "Нулевая пика",
    "Gravity Mines" to "Гравитационные мины",
    "Ion Swarm" to "Ионный рой",
    "Rift Blades" to "Клинки разлома",
    "Arc Coil" to "Дуговая катушка",
    "Quasar Cannon" to "Квазарная пушка",
    "Entropy Field" to "Поле энтропии",
    "Singularity Spear" to "Копьё сингулярности",
    "Prism Relay" to "Призменный ретранслятор",
    "High-speed movement leaves a damaging trail that lingers behind the Core." to "На высокой скорости Ядро оставляет за собой след, который некоторое время наносит урон.",
    "A heavy orbital mass converts velocity and mass into crushing contact damage." to "Тяжёлая масса на орбите превращает скорость и массу в сокрушительный урон при контакте.",
    "A pulsing gravity ring damages enemies held near its unstable perimeter." to "Пульсирующее гравитационное кольцо поражает врагов у своего нестабильного края.",
    "Momentum periodically projects a piercing lance along the Core's travel vector." to "Импульс периодически выпускает пробивающую пику по направлению движения Ядра.",
    "Braking plants implosive mines that pull enemies inward before detonating." to "Торможение устанавливает мины, которые притягивают врагов перед взрывом.",
    "Autonomous ion motes orbit the Core, seek targets, and accelerate with attack speed." to "Автономные ионные частицы вращаются вокруг Ядра, ищут цели и ускоряются вместе со скоростью атаки.",
    "Paired blades tear outward through enemies and return across their original paths." to "Парные клинки пронзают врагов и возвращаются по исходным траекториям.",
    "Stored kinetic charge erupts as lightning that chains between nearby enemies." to "Накопленный кинетический заряд превращается в молнию, перескакивающую между ближайшими врагами.",
    "A slow-charging cannon compresses momentum into a colossal piercing projectile." to "Медленно заряжающаяся пушка сжимает импульс в огромный пробивающий снаряд.",
    "A widening decay field slows hostile motion and deals escalating damage over time." to "Расширяющееся поле распада замедляет врагов и наносит возрастающий урон со временем.",
    "Every overdrive cycle forges a boss-piercing spear from condensed kinetic matter." to "Каждый цикл перегрузки создаёт из сжатой кинетической материи копьё, пробивающее боссов.",
    "Launches a seeking light shard that refracts between targets; mastery adds ricochets and twin relays." to "Выпускает самонаводящийся осколок света, преломляющийся между целями. Мастерство добавляет рикошеты и парные ретрансляторы.",
    "MOMENTUM" to "ИМПУЛЬС",
    "TRAIL" to "СЛЕД",
    "AREA" to "ОБЛАСТЬ",
    "ORBITAL" to "ОРБИТА",
    "IMPACT" to "УДАР",
    "MASS" to "МАССА",
    "AURA" to "АУРА",
    "CONTROL" to "КОНТРОЛЬ",
    "PHASE" to "ФАЗА",
    "PIERCE" to "ПРОБИТИЕ",
    "DIRECTIONAL" to "НАПРАВЛЕНИЕ",
    "MINE" to "МИНА",
    "PULL" to "ПРИТЯЖЕНИЕ",
    "BRAKE" to "ТОРМОЖЕНИЕ",
    "DRONE" to "ДРОН",
    "SEEKING" to "САМОНАВЕДЕНИЕ",
    "RAPID" to "СКОРОСТРЕЛЬНОСТЬ",
    "BLADE" to "КЛИНОК",
    "RETURNING" to "ВОЗВРАТ",
    "CRITICAL" to "КРИТИЧЕСКИЙ",
    "CHAIN" to "ЦЕПЬ",
    "LIGHTNING" to "МОЛНИЯ",
    "CHARGE" to "ЗАРЯД",
    "HEAVY" to "ТЯЖЁЛЫЙ",
    "DECAY" to "РАСПАД",
    "SLOW" to "ЗАМЕДЛЕНИЕ",
    "ULTIMATE" to "ВЫСШАЯ СИЛА",
    "OVERDRIVE" to "ПЕРЕГРУЗКА",
    "BOSS" to "БОСС",
    "RICOCHET" to "РИКОШЕТ",
    "REFRACTION" to "ПРЕЛОМЛЕНИЕ",
    "Core Integrity" to "Прочность Ядра",
    "Kinetic Amplifier" to "Кинетический усилитель",
    "Magnetic Resonance" to "Магнитный резонанс",
    "Cryo Vents" to "Криовентиляция",
    "Dash Capacitor" to "Конденсатор рывка",
    "Salvage Protocol" to "Протокол утилизации",
    "Data Archive" to "Архив данных",
    "Armory License" to "Лицензия арсенала",
    "+10 maximum integrity at the start of every run." to "+10 к максимальной прочности в начале каждого забега.",
    "+5% collision damage at the start of every run." to "+5% к урону от столкновений в начале каждого забега.",
    "+4% magnetic pull strength at the start of every run." to "+4% к силе магнитного притяжения в начале каждого забега.",
    "+5% heat dissipation at the start of every run." to "+5% к рассеиванию тепла в начале каждого забега.",
    "+5% dash impulse at the start of every run." to "+5% к импульсу рывка в начале каждого забега.",
    "+5% Kinetic Matter gained during runs." to "+5% к получаемой в забегах кинетической материи.",
    "+5% Data gained during runs." to "+5% к получаемым в забегах данным.",
    "+4% weapon power per rank." to "+4% к мощности оружия за ранг.",
    "Vector maneuver" to "Векторный манёвр",
    "Real turns charge the next primary hit and ease Dash heat." to "Повороты заряжают следующее основное попадание и снижают нагрев от рывка.",
    "Gravitic grouping" to "Гравитационная группировка",
    "Primary hits periodically pull nearby enemies into a group." to "Основные попадания периодически стягивают ближайших врагов в группу.",
    "Ion discharge" to "Ионный разряд",
    "Primary hits periodically discharge into up to two other enemies." to "Основные попадания периодически поражают разрядом до двух других врагов.",
    "Rift echo" to "Эхо разлома",
    "Primary hits leave a bounded delayed hit on their target." to "Основные попадания оставляют на цели ограниченный отложенный удар.",
    "Prism refraction" to "Призменное преломление",
    "Primary hits periodically refract into a nearby second target." to "Основные попадания периодически преломляются в соседнюю цель.",
    "Entropy decay" to "Энтропийный распад",
    "Primary hits apply a brief decay that cannot trigger another synergy." to "Основные попадания вызывают краткий распад, который не активирует другие синергии.",
    "Brake compression" to "Тормозное сжатие",
    "A hit charged by real braking becomes a compression wave." to "Попадание, заряженное торможением, превращается в волну сжатия.",
    "Linked echo" to "Связанное эхо",
    "A delayed echo repeats its saved discharge link, even if a nearer target appears." to "Отложенное эхо повторяет сохранённую связь разряда, даже если появилась более близкая цель.",
    "Witness transfer" to "Передача свидетельства",
    "The death of a marked target transfers a bounded portion of its decay once." to "Гибель помеченной цели однократно передаёт ограниченную часть её распада.",
    "Ghost mirror" to "Призрачное зеркало",
    "A real Dash leaves a short-lived edge that refracts the next primary hit." to "Рывок оставляет недолговечную грань, преломляющую следующее основное попадание.",
    "Charged anchor" to "Заряженный якорь",
    "An anchor holds a dead target's remaining charge until a delayed collapse." to "Якорь удерживает остаточный заряд погибшей цели до отложенного схлопывания.",
    "Fracture decay" to "Распад разлома",
    "A target displaced by Fracture Gate leaves a brief slowing decay trail." to "Цель, перемещённая Вратами разлома, оставляет краткий замедляющий след распада.",
    "Motion" to "Движение",
    "Control" to "Контроль",
    "Strike" to "Удар",
    "Offense" to "Атака",
    "Defense" to "Защита",
    "Economy" to "Экономика",
    "Resonant circuit" to "Резонансный контур",
    "Visit beacons 2, 3, then return to 1." to "Посетите маяки 2 и 3, затем вернитесь к маяку 1.",
    "Sealed anomaly" to "Запечатанная аномалия",
    "Defeat the three marked defenders near the vault." to "Победите трёх отмеченных защитников возле хранилища.",
    "Collapsing orbit" to "Схлопывающаяся орбита",
    "Move within the ring for eight seconds; dodge marked volleys." to "Двигайтесь внутри кольца восемь секунд и уклоняйтесь от отмеченных залпов.",
    "Impact power" to "Сила столкновений",
    "Activation speed" to "Скорость активации",
    "Integrity" to "Прочность",
    "Shield" to "Щит",
    "Regeneration" to "Восстановление",
    "Dash impulse" to "Импульс рывка",
    "Dash heat" to "Нагрев рывка",
    "Critical power" to "Сила критического удара",
    "Drift" to "Дрейф",
    "Surge" to "Разгон",
    "Hyper" to "Гиперскорость",
    "DRIFT PHASE" to "ФАЗА ДРЕЙФА",
    "THE ARCHITECT" to "АРХИТЕКТОР",
    "KINETIC OVERDRIVE" to "КИНЕТИЧЕСКАЯ ПЕРЕГРУЗКА",
    "DASH ONLINE" to "РЫВОК ГОТОВ",
    "OVERHEAT" to "ПЕРЕГРЕВ",
    "SINGULARITY CONTACT" to "КОНТАКТ С СИНГУЛЯРНОСТЬЮ",
    "POLARITY FIELD STRAIN" to "ПОЛЕ ПОЛЯРНОСТИ ПЕРЕНАПРЯЖЕНО",
    "ARCHITECT DISMANTLED" to "АРХИТЕКТОР РАЗОБРАН",
    "CATALOG COMPLETE // MATTER SALVAGED" to "КАТАЛОГ ЗАВЕРШЁН // МАТЕРИЯ ИЗВЛЕЧЕНА",
    "CORE FRACTURED" to "ЯДРО РАЗРУШЕНО",
    "ELITE KEY ACQUIRED" to "ПОЛУЧЕН ЭЛИТНЫЙ КЛЮЧ",
    "RELIC RESONANCE" to "РЕЗОНАНС РЕЛИКВИИ",
    "TOTEM DETECTED" to "ОБНАРУЖЕН ТОТЕМ",
    "ELITE SIGNAL" to "ЭЛИТНЫЙ СИГНАЛ",
    "TWO ANOMALIES DETECTED // CHOOSE A COURSE" to "ОБНАРУЖЕНЫ ДВЕ АНОМАЛИИ // ВЫБЕРИТЕ ПУТЬ",
    "ANOMALY LOST" to "АНОМАЛИЯ УТРАЧЕНА",
    "ANOMALY RESOLVED" to "АНОМАЛИЯ ЗАВЕРШЕНА",
    "Change weapon" to "Сменить оружие",
    "Recalibrate the Totem, then choose one of three different weapon systems." to "Перенастройте Тотем и выберите одну из трёх других оружейных систем.",
    "RECALIBRATE" to "ПЕРЕНАСТРОЙКА",
    "Meld resonance" to "Слить резонанс",
    "MELD" to "СЛИЯНИЕ",
    "REPLACE" to "ЗАМЕНА",
    "RESONANCE SALVAGED" to "РЕЗОНАНС УТИЛИЗИРОВАН",
    "BOUND" to "ПРИВЯЗАНО",
    "SALVAGED" to "УТИЛИЗИРОВАНО",
    "RESONANCE" to "РЕЗОНАНС",
    "ACQUIRED" to "ПОЛУЧЕНО",
    "SYNCHRONIZED" to "СИНХРОНИЗИРОВАНО",
    "Choose a direction, then one of three matching offers." to "Выберите направление, затем одно из трёх подходящих предложений.",
    "FOCUS" to "НАПРАВЛЕНИЕ",
    "Raise current weapon mastery by one level." to "Повысьте мастерство текущего оружия на один уровень.",
    "AMPLIFY" to "УСИЛЕНИЕ",
    "CHANGE" to "СМЕНА",
    "/s" to "/с",
    "s" to "с",
)
