// SPDX-FileCopyrightText: 2026 Vladislav Tomilov
// SPDX-License-Identifier: GPL-3.0-or-later

package kinetickk.ball.content.api

internal val RelicPhrasesInRussian: Map<String, String> = mapOf(
    "Kinetic Flywheel" to "Кинетический маховик",
    "The weapon stores excess velocity as striking force instead of losing it to drag." to "Оружие сохраняет избыточную скорость как силу удара, вместо того чтобы терять её из-за сопротивления.",
    "+5% weapon damage above 500 u/s per rank; the bonus doubles above 1,600 u/s." to "+5% к урону оружия за ранг при скорости выше 500 ед/с; выше 1 600 ед/с бонус удваивается.",
    "Ghost Vector" to "Призрачный вектор",
    "Every dash leaves a cutting vector through enemies near the Core's departure point." to "Каждый рывок оставляет режущий вектор среди врагов возле точки отправления Ядра.",
    "+24 dash-cut damage and +14 effect radius per rank." to "+24 к урону разреза при рывке и +14 к радиусу эффекта за ранг.",
    "Overtake Protocol" to "Протокол обгона",
    "The weapon predicts hostile motion and punishes enemies that refuse to slow down." to "Оружие предсказывает движение врагов и наказывает тех, кто не сбавляет скорость.",
    "+7% weapon damage per rank against enemies moving at 170 u/s or faster." to "+7% к урону оружия за ранг по врагам, движущимся со скоростью от 170 ед/с.",
    "Slipstream Relay" to "Ретранслятор потока",
    "Kills made at high velocity feed a short activation surge into the next weapon cycle." to "Убийства на высокой скорости ненадолго ускоряют активацию следующего оружейного цикла.",
    "+6% activation speed per rank for 3 seconds after a kill above 500 u/s." to "+6% к скорости активации за ранг на 3 секунды после убийства при скорости выше 500 ед/с.",
    "Brakepoint Memory" to "Память торможения",
    "Gravity Brake stores arrested momentum; the next weapon contact releases it all at once." to "Гравитационный тормоз сохраняет погашенный импульс; следующее попадание оружия высвобождает его целиком.",
    "Stores up to +18% next-hit damage per rank while braking." to "Во время торможения накапливает до +18% урона следующего попадания за ранг.",
    "Polarity Sling" to "Праща полярности",
    "A strained tether slings weapon force through the weakest point in the magnetic field." to "Напряжённая связь направляет силу оружия через слабейшую точку магнитного поля.",
    "Up to +8% weapon damage per rank as Polarity falls toward zero." to "До +8% к урону оружия за ранг по мере снижения полярности до нуля.",
    "Orbital Nail" to "Орбитальный гвоздь",
    "Weapon contact nails a target to the Core's local gravity well." to "Попадание оружия прибивает цель к локальной гравитационной яме Ядра.",
    "Pulls the target 24 u/s toward the Core per rank on each qualified hit." to "Каждое учитываемое попадание притягивает цель к Ядру со скоростью 24 ед/с за ранг.",
    "Eventide Anchor" to "Сумеречный якорь",
    "Destroyed enemies collapse into brief anchors that drag their formation inward." to "Уничтоженные враги ненадолго превращаются в якоря, стягивающие строй противника к центру.",
    "+18 implosion damage and +18 radius per rank on kill." to "При убийстве: +18 к урону схлопывания и +18 к радиусу за ранг.",
    "Periapsis Hook" to "Крюк перицентра",
    "Distant targets fall harder through the weapon's curved approach." to "Далёкие цели сильнее страдают от изогнутой траектории оружия.",
    "+8% weapon damage per rank beyond 300 units from the Core." to "+8% к урону оружия за ранг по целям дальше 300 единиц от Ядра.",
    "Crush Depth" to "Глубинное сжатие",
    "Targets deep inside the Core's pressure field are compressed before impact." to "Цели в глубине поля давления Ядра сжимаются ещё до удара.",
    "+6% weapon damage per rank within 155 units of the Core." to "+6% к урону оружия за ранг в пределах 155 единиц от Ядра.",
    "Mass Echo" to "Эхо массы",
    "The weapon borrows the Core's mass and returns it as recoil through its victim." to "Оружие заимствует массу Ядра и возвращает её отдачей через жертву.",
    "+4% damage per Core mass and stronger knockback per rank." to "+4% к урону на единицу массы Ядра и усиленное отбрасывание за ранг.",
    "Tidal Lock" to "Приливный захват",
    "Repeated contacts align the weapon and target into an increasingly violent orbit." to "Повторные попадания связывают оружие и цель во всё более разрушительную орбиту.",
    "+2% damage per rank and qualified hit, stacking five times per target." to "+2% к урону за ранг и учитываемое попадание; складывается до пяти раз на каждой цели.",
    "Voltaic Filament" to "Вольтовая нить",
    "Weapon contact extrudes a live filament toward the nearest untouched enemy." to "Попадание оружия вытягивает токопроводящую нить к ближайшему незатронутому врагу.",
    "Arcs 16% of the triggering damage per rank, with a 0.28-second gate." to "Передаёт разрядом 16% исходного урона за ранг с интервалом не менее 0,28 секунды.",
    "Static Chorus" to "Статический хор",
    "A rhythm of weapon contacts resolves into a many-voiced discharge." to "Ритм попаданий оружия складывается в многоголосый разряд.",
    "Every seventh qualified hit arcs to 1 additional target per rank." to "Каждое седьмое учитываемое попадание поражает разрядом ещё 1 цель за ранг.",
    "Ion Debt" to "Ионный долг",
    "Each contact leaves charge the target must eventually repay to everything nearby." to "Каждое попадание оставляет заряд, который цель рано или поздно вернёт всему вокруг.",
    "Five qualified hits discharge 14 area damage per rank." to "Пять учитываемых попаданий вызывают разряд с уроном по области 14 за ранг.",
    "Circuit Breaker" to "Размыкатель цепи",
    "The first weapon contact interrupts a target's movement circuit and cracks its guard." to "Первое попадание оружия размыкает двигательную цепь цели и пробивает её защиту.",
    "+11 opening damage and 8% movement interruption per rank." to "+11 к урону первого попадания и 8% прерывания движения за ранг.",
    "Return Circuit" to "Возвратный контур",
    "When no nearby body can carry the current onward, it folds back through its first host." to "Если рядом нет тела для передачи тока, он возвращается через первую цель.",
    "+9% weapon damage per rank against isolated targets." to "+9% к урону оружия за ранг по изолированным целям.",
    "Storm Index" to "Индекс бури",
    "At Surge velocity, the weapon indexes every fourth contact as a free lightning route." to "На скорости разгона оружие превращает каждое четвёртое попадание в бесплатный путь молнии.",
    "+10 arc damage and +45 acquisition range per rank." to "+10 к урону разряда и +45 к дальности захвата за ранг.",
    "Echo Chamber" to "Камера эха",
    "A portion of every strike is hidden outside time and returned after the target has moved." to "Часть каждого удара скрывается вне времени и возвращается после перемещения цели.",
    "Repeats 12% of qualified-hit damage per rank after 0.45 seconds." to "Повторяет 12% урона учитываемого попадания за ранг через 0,45 секунды.",
    "Palimpsest Round" to "Снаряд-палимпсест",
    "The weapon periodically writes its previous impact over the present one." to "Оружие периодически записывает предыдущее попадание поверх текущего.",
    "Every seventh qualified hit repeats 20% of that damage per rank." to "Каждое седьмое учитываемое попадание повторяет 20% этого урона за ранг.",
    "Second Hand" to "Секундная стрелка",
    "A kill steals a fraction of the next second and hands it to the weapon clock." to "Убийство крадёт долю следующей секунды и передаёт её часам оружия.",
    "Removes 0.08 seconds per rank from both weapon cooldowns on kill." to "При убийстве сокращает обе перезарядки оружия на 0,08 секунды за ранг.",
    "Fracture Gate" to "Врата разлома",
    "A repeating contact folds its target through the Core and ruptures its exit point." to "Повторное попадание переносит цель сквозь Ядро и разрывает точку её выхода.",
    "Every sixth qualified hit transposes the target and deals 12 rupture damage per rank." to "Каждое шестое учитываемое попадание переносит цель и наносит 12 урона разрывом за ранг.",
    "Split Horizon" to "Расколотый горизонт",
    "A destroyed enemy leaves one half of its final strike hunting beyond the horizon." to "Уничтоженный враг оставляет половину последнего удара охотиться за горизонтом.",
    "Kills launch a seeking shard for 18 damage per rank." to "Убийства выпускают самонаводящийся осколок с уроном 18 за ранг.",
    "Borrowed Moment" to "Заёмный миг",
    "Damage to the Core is answered with a brief interval stolen from the attacker." to "В ответ на урон Ядро крадёт у нападающего короткий промежуток времени.",
    "+9% activation speed per rank for 2.5 seconds after taking damage." to "+9% к скорости активации за ранг на 2,5 секунды после получения урона.",
    "Glass Witness" to "Стеклянный свидетель",
    "The first strike is remembered as a fault line that later hits can see and exploit." to "Первый удар оставляет линию разлома, которую последующие попадания находят и используют.",
    "Exposes fresh targets to +7% weapon damage per rank for 3 seconds." to "Свежие цели получают на 7% больше урона оружия за ранг в течение 3 секунд.",
    "Fracture Lens" to "Линза разлома",
    "Existing wounds bend probability until the weapon finds the most brittle outcome." to "Существующие раны искривляют вероятность, пока оружие не найдёт самый хрупкий исход.",
    "+2.5% critical chance per rank against injured targets." to "+2,5% к шансу критического удара за ранг по раненым целям.",
    "Spectral Fan" to "Спектральный веер",
    "A regular cadence of impacts fans one strike into two pale refractions." to "Ритмичные попадания расщепляют один удар на два бледных преломления.",
    "Every sixth qualified hit refracts 14% damage per rank into two nearby targets." to "Каждое шестое учитываемое попадание преломляет 14% урона за ранг в две соседние цели.",
    "Hardlight Edge" to "Грань твёрдого света",
    "Critical strikes condense into an edge too coherent to disperse on contact." to "Критические удары сгущаются в грань, слишком цельную, чтобы рассеяться при контакте.",
    "+12% critical damage per rank." to "+12% к критическому урону за ранг.",
    "Chroma Feedback" to "Хроматическая обратная связь",
    "The first color returned by each enemy is recycled into the Core's defenses." to "Первый цвет, отражённый каждым врагом, перерабатывается в защиту Ядра.",
    "First contact restores 1.5 Shield—or 2 Overdrive—per rank." to "Первое попадание восстанавливает 1,5 щита или 2 перегрузки за ранг.",
    "Mirror Cut" to "Зеркальный разрез",
    "A critical wound appears again in the nearest body as if both occupied one reflection." to "Критическая рана появляется и на ближайшем теле, словно обе цели занимают одно отражение.",
    "Critical hits mirror 15% of their damage per rank to another target." to "Критические попадания отражают 15% своего урона за ранг в другую цель.",
    "Heat Debt" to "Тепловой долг",
    "Weapon damage is not spent; it accumulates as an unstable debt inside the target." to "Урон оружия не исчезает, а накапливается внутри цели в виде нестабильного долга.",
    "Qualified hits build debt that ruptures for 16 area damage per rank." to "Учитываемые попадания накапливают долг, который взрывается с уроном по области 16 за ранг.",
    "Scar Tissue" to "Рубцовая ткань",
    "Each strike teaches the target's structure how to keep damaging itself." to "Каждый удар учит структуру цели продолжать разрушать саму себя.",
    "Applies 3 damage per second per rank for 3 seconds; repeated hits intensify it." to "Наносит 3 урона в секунду за ранг в течение 3 секунд; повторные попадания усиливают эффект.",
    "Quietus Bloom" to "Цветение покоя",
    "A kill blossoms into a field that ages motion and matter around it." to "Убийство рождает поле, состаривающее движение и материю вокруг.",
    "+10 decay damage, +10% slow, and +16 radius per rank on kill." to "При убийстве: +10 к урону распада, +10% к замедлению и +16 к радиусу за ранг.",
    "Devourer's Toll" to "Пошлина пожирателя",
    "Every death pays a small portion of its remaining possibility back to the Core." to "Каждая смерть возвращает Ядру малую часть оставшихся возможностей.",
    "Every third kill restores 1.5 Integrity and Shield per rank." to "Каждое третье убийство восстанавливает 1,5 прочности и щита за ранг.",
    "Doom Clock" to "Часы рока",
    "Elite systems and the Architect are forced to acknowledge how little time they have left." to "Элитные системы и Архитектор вынуждены признать, как мало времени им осталось.",
    "+8% damage per rank to Elites and the Architect, rising with run time." to "+8% к урону по элитным врагам и Архитектору за ранг; бонус растёт со временем забега.",
    "Last Light" to "Последний свет",
    "Near fracture, the Core burns its final safe future to make the current one lethal." to "На грани разрушения Ядро сжигает своё последнее безопасное будущее, делая настоящее смертоносным.",
    "+12% weapon damage and +8% activation speed per rank below 35% Integrity." to "+12% к урону оружия и +8% к скорости активации за ранг при прочности ниже 35%.",
    "Agony Scepter" to "Скипетр агонии",
    "The Scepter discovers a forbidden extension unique to whichever weapon is synchronized." to "Скипетр открывает запретное расширение, уникальное для синхронизированного оружия.",
    "Strengthens the weapon-specific mutation per rank; all twelve weapons mutate differently." to "Каждый ранг усиливает уникальную мутацию оружия; все двенадцать видов мутируют по-разному.",
    "Crown of Four Winds" to "Корона четырёх ветров",
    "The Crown rewards a matrix whose four slots disagree without falling out of resonance." to "Корона награждает матрицу, в которой четыре ячейки различаются, сохраняя общий резонанс.",
    "+4% damage and +3% activation speed per rank for each distinct non-Sovereign aspect." to "+4% к урону и +3% к скорости активации за ранг за каждый уникальный аспект, кроме Владычества.",
    "Mirror of the Hunt" to "Зеркало охоты",
    "The first wound in every enemy is reflected into a second enemy across the Core." to "Первая рана каждого врага отражается на второго врага по другую сторону Ядра.",
    "The reflected opening strike carries 20% of its damage per rank." to "Отражённый первый удар переносит 20% своего урона за ранг.",
    "Engine of Paradox" to "Двигатель парадокса",
    "Entering Overdrive rewinds the weapon and vents heat from a future that never happened." to "Начало перегрузки отматывает оружие назад и отводит тепло из несбывшегося будущего.",
    "On Overdrive: reset cooldowns, vent 10 Heat, and gain 10% activation speed per rank." to "При перегрузке: сброс перезарядок, отвод 10 тепла и +10% к скорости активации за ранг.",
)
