// SPDX-FileCopyrightText: 2026 Vladislav Tomilov
// SPDX-License-Identifier: GPL-3.0-or-later

package kinetickk.ball.profile.interaction.localization

internal object EnglishProfileText {
    operator fun get(key: ProfileText): String = when (key) {
        ProfileText.SettingsInterface -> "Interface"
        ProfileText.RunStatisticsSide -> "Run statistics side"
        ProfileText.LeftSide -> "Left"
        ProfileText.RightSide -> "Right"
        ProfileText.PreviousPage -> "Previous page"
        ProfileText.NextPage -> "Next page"
        ProfileText.SettingsTitle -> "Settings"
        ProfileText.SettingsGame -> "Game"
        ProfileText.SettingsSound -> "Sound"
        ProfileText.VolumePercent -> "Volume in percent, 0–100"
        ProfileText.SettingsGraphics -> "Graphics"
        ProfileText.Language -> "Language"
        ProfileText.Sfx -> "Sfx"
        ProfileText.Music -> "Music"
        ProfileText.MasterVolume -> "Master volume"
        ProfileText.SimulationSpeed -> "Simulation speed"
        ProfileText.TextSize -> "Text size"
        ProfileText.ScreenShake -> "Screen shake"
        ProfileText.Particles -> "Particles"
        ProfileText.DamageNumbers -> "Damage numbers"
        ProfileText.DamageNumberSize -> "Damage number size"
        ProfileText.DamageNumberFormat -> "Damage number format"
        ProfileText.DamageColorTiers -> "Damage color tiers"
        ProfileText.On -> "On"
        ProfileText.Off -> "Off"
        ProfileText.Low -> "Low"
        ProfileText.Normal -> "Normal"
        ProfileText.High -> "High"
        ProfileText.Small -> "Small"
        ProfileText.Large -> "Large"
        ProfileText.Huge -> "Huge"
        ProfileText.Compact -> "Compact"
        ProfileText.Full -> "Full"
        ProfileText.ArmoryTitle -> "Armory"
        ProfileText.LabTitle -> "Upgrades"
        ProfileText.MaximumSynchrony -> "Max"
        ProfileText.RebirthTitle -> "Rebirth"
        ProfileText.HostileEscalation -> "Hostile escalation"
        ProfileText.OpeningHostiles -> "Opening hostiles"
        ProfileText.EnemyCap -> "Active enemy cap"
        ProfileText.SpawnRate -> "Spawn rate"
        ProfileText.EnemyIntegrity -> "Enemy integrity"
        ProfileText.EnemySpeed -> "Enemy speed"
        ProfileText.IncomingDamage -> "Incoming damage"
        ProfileText.CycleCompensation -> "Cycle compensation"
        ProfileText.ThreatAdvance -> "Threat advance"
        ProfileText.PlayerPower -> "Player power"
        ProfileText.CoreIntegrity -> "Core integrity"
        ProfileText.KineticMatter -> "Kinetic matter"
        ProfileText.BonusRerolls -> "Bonus rerolls"
        ProfileText.Seconds -> "+{0}s"
    }
}
