// SPDX-FileCopyrightText: 2026 Vladislav Tomilov
// SPDX-License-Identifier: GPL-3.0-or-later

package kinetickk.ball.profile.interaction.localization

internal object EnglishProfileText {
    operator fun get(key: ProfileText): String = when (key) {
        ProfileText.SettingsInterface -> "Interface"
        ProfileText.RunStatisticsSide -> "Run statistics side"
        ProfileText.LeftSide -> "Left"
        ProfileText.RightSide -> "Right"
        ProfileText.Back -> "Back · Esc"
        ProfileText.PreviousPage -> "Previous page"
        ProfileText.NextPage -> "Next page"
        ProfileText.SettingsTitle -> "System settings"
        ProfileText.SettingsHint -> "− / + adjust"
        ProfileText.SettingsGame -> "Game"
        ProfileText.SettingsSound -> "Sound"
        ProfileText.SettingsSoundHint -> "Drag the slider or enter 0–100%"
        ProfileText.VolumePercent -> "Volume in percent, 0–100"
        ProfileText.SettingsGraphics -> "Graphics"
        ProfileText.SettingsDamageHint -> "− / + adjust // damage heat: yellow > red"
        ProfileText.Language -> "Language"
        ProfileText.Sfx -> "Sfx"
        ProfileText.Music -> "Music"
        ProfileText.MasterVolume -> "Master volume"
        ProfileText.SimulationSpeed -> "Simulation speed"
        ProfileText.TextSize -> "Text size"
        ProfileText.ScreenShake -> "Screen shake"
        ProfileText.Particles -> "Particles"
        ProfileText.DamageNumbers -> "Damage numbers"
        ProfileText.DamageNumberSize -> "Damage number size"
        ProfileText.DamageNumberFormat -> "Damage number format"
        ProfileText.DamageColorTiers -> "Damage color tiers"
        ProfileText.On -> "On"
        ProfileText.Off -> "Off"
        ProfileText.Low -> "Low"
        ProfileText.Normal -> "Normal"
        ProfileText.High -> "High"
        ProfileText.Small -> "Small"
        ProfileText.Large -> "Large"
        ProfileText.Huge -> "Huge"
        ProfileText.Compact -> "Compact"
        ProfileText.Full -> "Full"
        ProfileText.ArmoryTitle -> "Weapon armory"
        ProfileText.ArmorySummary -> "Unlocked {1}/{0} · Matter {2}"
        ProfileText.Milestones -> "Milestones boost damage + activation"
        ProfileText.Equipped -> "Equipped loadout"
        ProfileText.ActiveRun -> "Active this run"
        ProfileText.Equip -> "Equip"
        ProfileText.Unlock -> "Unlock {0}"
        ProfileText.MasteryLevel -> "L{0} {1}"
        ProfileText.LabTitle -> "Upgrades"
        ProfileText.LabSummary -> "Matter {0}"
        ProfileText.Rank -> "{0}/{1}"
        ProfileText.MaximumSynchrony -> "Max"
        ProfileText.BuyMatter -> "{0} ◇"
        ProfileText.RebirthTitle -> "Rebirth protocol"
        ProfileText.ThreatTier -> "Tier {0} → {1}"
        ProfileText.CurrentCycle -> "Current"
        ProfileText.NextCycle -> "Next"
        ProfileText.ResetBuild -> "Your run build will be reset"
        ProfileText.Kept -> "Matter, upgrades and unlocked weapons are kept"
        ProfileText.LifetimeKept -> "Discoveries and settings are kept"
        ProfileText.MaxRebirth -> "Maximum rebirth tier"
        ProfileText.LockedRebirth -> "Rebirth locked"
        ProfileText.ConfirmRebirth -> "Confirm tier {0}"
        ProfileText.ArmRebirth -> "Advance to tier {1}"
        ProfileText.AllDirectives -> "All threat directives cleared"
        ProfileText.DefeatArchitect -> "Defeat the architect on tier {0}"
        ProfileText.SecondPress -> "Second press resets the run build"
        ProfileText.FirstPress -> "First press arms this transition"
        ProfileText.TierDirective -> "{0} · {1}"
        ProfileText.HostileEscalation -> "Hostile escalation"
        ProfileText.OpeningHostiles -> "Opening hostiles"
        ProfileText.EnemyCap -> "Active enemy cap"
        ProfileText.SpawnRate -> "Spawn rate"
        ProfileText.EnemyIntegrity -> "Enemy integrity"
        ProfileText.EnemySpeed -> "Enemy speed"
        ProfileText.IncomingDamage -> "Incoming damage"
        ProfileText.CycleCompensation -> "Cycle compensation"
        ProfileText.ThreatAdvance -> "Threat advance"
        ProfileText.PlayerPower -> "Player power"
        ProfileText.CoreIntegrity -> "Core integrity"
        ProfileText.KineticMatter -> "Kinetic matter"
        ProfileText.BonusRerolls -> "Bonus rerolls"
        ProfileText.Seconds -> "+{0}s"
    }
}
