// SPDX-FileCopyrightText: 2026 Vladislav Tomilov
// SPDX-License-Identifier: GPL-3.0-or-later

package kinetickk.ball.profile.interaction.localization

internal object EnglishProfileText {
    operator fun get(key: ProfileText): String = when (key) {
        ProfileText.SettingsTitle -> "SYSTEM SETTINGS"
        ProfileText.SettingsHint -> "− / + ADJUST // DAMAGE HEAT: YELLOW > RED"
        ProfileText.Language -> "LANGUAGE"
        ProfileText.Sfx -> "SFX"
        ProfileText.Music -> "MUSIC"
        ProfileText.MasterVolume -> "MASTER VOLUME"
        ProfileText.SimulationSpeed -> "SIMULATION SPEED"
        ProfileText.TextSize -> "TEXT SIZE"
        ProfileText.ScreenShake -> "SCREEN SHAKE"
        ProfileText.Particles -> "PARTICLES"
        ProfileText.DamageNumbers -> "DAMAGE NUMBERS"
        ProfileText.DamageNumberSize -> "DAMAGE NUMBER SIZE"
        ProfileText.DamageNumberFormat -> "DAMAGE NUMBER FORMAT"
        ProfileText.DamageColorTiers -> "DAMAGE COLOR TIERS"
        ProfileText.On -> "ON"
        ProfileText.Off -> "OFF"
        ProfileText.Low -> "LOW"
        ProfileText.Normal -> "NORMAL"
        ProfileText.High -> "HIGH"
        ProfileText.Small -> "SMALL"
        ProfileText.Large -> "LARGE"
        ProfileText.Huge -> "HUGE"
        ProfileText.Compact -> "COMPACT"
        ProfileText.Full -> "FULL"
        ProfileText.ArmoryTitle -> "WEAPON ARMORY"
        ProfileText.ArmorySummary -> "{0} SYSTEMS // {1} UNLOCKED // MATTER {2}"
        ProfileText.Milestones -> "MILESTONES BOOST DAMAGE + ACTIVATION"
        ProfileText.Equipped -> "EQUIPPED LOADOUT"
        ProfileText.ActiveRun -> "ACTIVE THIS RUN"
        ProfileText.Equip -> "EQUIP"
        ProfileText.Unlock -> "UNLOCK {0}"
        ProfileText.MasteryLevel -> "L{0} {1}"
        ProfileText.LabTitle -> "KINETIC LAB"
        ProfileText.LabSummary -> "PERMANENT RESEARCH // MATTER {0}"
        ProfileText.Rank -> "RANK {0}/{1}"
        ProfileText.MaximumSynchrony -> "MAXIMUM SYNCHRONY"
        ProfileText.BuyMatter -> "BUY {0} MATTER"
        ProfileText.RebirthTitle -> "REBIRTH PROTOCOL"
        ProfileText.ThreatTier -> "PERMANENT THREAT // TIER {0} > {1}"
        ProfileText.CurrentCycle -> "CURRENT CYCLE"
        ProfileText.NextCycle -> "NEXT CYCLE"
        ProfileText.ResetBuild -> "RESET: RUN BUILD"
        ProfileText.Kept -> "KEPT: MATTER // LAB // ARMORY // CODEX"
        ProfileText.LifetimeKept -> "LIFETIME UNLOCKS + SETTINGS ALSO REMAIN"
        ProfileText.MaxRebirth -> "MAXIMUM REBIRTH TIER"
        ProfileText.LockedRebirth -> "REBIRTH LOCKED"
        ProfileText.ConfirmRebirth -> "CONFIRM REBIRTH // ENTER TIER {0}"
        ProfileText.ArmRebirth -> "ARM REBIRTH // TIER {0} > {1}"
        ProfileText.AllDirectives -> "ALL THREAT DIRECTIVES CLEARED"
        ProfileText.DefeatArchitect -> "DEFEAT THE ARCHITECT ON TIER {0}"
        ProfileText.SecondPress -> "SECOND PRESS RESETS THE RUN BUILD"
        ProfileText.FirstPress -> "FIRST PRESS ARMS THIS TRANSITION"
        ProfileText.TierDirective -> "TIER {0} // {1}"
        ProfileText.HostileEscalation -> "HOSTILE ESCALATION"
        ProfileText.OpeningHostiles -> "OPENING HOSTILES"
        ProfileText.EnemyCap -> "ACTIVE ENEMY CAP"
        ProfileText.SpawnRate -> "SPAWN RATE"
        ProfileText.EnemyIntegrity -> "ENEMY INTEGRITY"
        ProfileText.EnemySpeed -> "ENEMY SPEED"
        ProfileText.IncomingDamage -> "INCOMING DAMAGE"
        ProfileText.CycleCompensation -> "CYCLE COMPENSATION"
        ProfileText.ThreatAdvance -> "THREAT ADVANCE"
        ProfileText.PlayerPower -> "PLAYER POWER"
        ProfileText.CoreIntegrity -> "CORE INTEGRITY"
        ProfileText.KineticMatter -> "KINETIC MATTER"
        ProfileText.BonusRerolls -> "BONUS REROLLS"
        ProfileText.Seconds -> "+{0}s"
    }
}
