// SPDX-FileCopyrightText: 2026 Vladislav Tomilov
// SPDX-License-Identifier: GPL-3.0-or-later

package kinetickk.ball.profile.interaction.localization

import kinetickk.foundation.common.localization.TextResource

internal enum class ProfileText : TextResource {
    SettingsTitle,
    SettingsHint,
    Language,
    Sfx,
    Music,
    MasterVolume,
    SimulationSpeed,
    TextSize,
    ScreenShake,
    Particles,
    DamageNumbers,
    DamageNumberSize,
    DamageNumberFormat,
    DamageColorTiers,
    On,
    Off,
    Low,
    Normal,
    High,
    Small,
    Large,
    Huge,
    Compact,
    Full,
    ArmoryTitle,
    ArmorySummary,
    Milestones,
    Equipped,
    ActiveRun,
    Equip,
    Unlock,
    MasteryLevel,
    LabTitle,
    LabSummary,
    Rank,
    MaximumSynchrony,
    BuyMatter,
    RebirthTitle,
    ThreatTier,
    CurrentCycle,
    NextCycle,
    ResetBuild,
    Kept,
    LifetimeKept,
    MaxRebirth,
    LockedRebirth,
    ConfirmRebirth,
    ArmRebirth,
    AllDirectives,
    DefeatArchitect,
    SecondPress,
    FirstPress,
    TierDirective,
    HostileEscalation,
    OpeningHostiles,
    EnemyCap,
    SpawnRate,
    EnemyIntegrity,
    EnemySpeed,
    IncomingDamage,
    CycleCompensation,
    ThreatAdvance,
    PlayerPower,
    CoreIntegrity,
    KineticMatter,
    BonusRerolls,
    Seconds;

    override val english: String get() = EnglishProfileText[this]
    override val russian: String get() = RussianProfileText[this]
}
