// SPDX-FileCopyrightText: 2026 Vladislav Tomilov
// SPDX-License-Identifier: GPL-3.0-or-later

package kinetickk.ball.profile.interaction.localization

internal object RussianProfileText {
    operator fun get(key: ProfileText): String = when (key) {
        ProfileText.SettingsTitle -> "НАСТРОЙКИ"
        ProfileText.SettingsHint -> "− / + ИЗМЕНИТЬ // УРОН: ЖЁЛТЫЙ > КРАСНЫЙ"
        ProfileText.Language -> "ЯЗЫК"
        ProfileText.Sfx -> "ЗВУКИ"
        ProfileText.Music -> "МУЗЫКА"
        ProfileText.MasterVolume -> "ОБЩАЯ ГРОМКОСТЬ"
        ProfileText.SimulationSpeed -> "СКОРОСТЬ ИГРЫ"
        ProfileText.TextSize -> "РАЗМЕР ТЕКСТА"
        ProfileText.ScreenShake -> "ТРЯСКА ЭКРАНА"
        ProfileText.Particles -> "ЧАСТИЦЫ"
        ProfileText.DamageNumbers -> "ЧИСЛА УРОНА"
        ProfileText.DamageNumberSize -> "РАЗМЕР ЧИСЕЛ"
        ProfileText.DamageNumberFormat -> "ФОРМАТ ЧИСЕЛ"
        ProfileText.DamageColorTiers -> "ЦВЕТ УРОНА"
        ProfileText.On -> "ВКЛ"
        ProfileText.Off -> "ВЫКЛ"
        ProfileText.Low -> "МАЛО"
        ProfileText.Normal -> "НОРМА"
        ProfileText.High -> "МНОГО"
        ProfileText.Small -> "МАЛЫЙ"
        ProfileText.Large -> "КРУПНЫЙ"
        ProfileText.Huge -> "ОГРОМНЫЙ"
        ProfileText.Compact -> "КРАТКО"
        ProfileText.Full -> "ПОЛНО"
        ProfileText.ArmoryTitle -> "АРСЕНАЛ"
        ProfileText.ArmorySummary -> "СИСТЕМ: {0} // ОТКРЫТО: {1} // МАТЕРИЯ: {2}"
        ProfileText.Milestones -> "МАСТЕРСТВО УСИЛИВАЕТ УРОН И АКТИВАЦИЮ"
        ProfileText.Equipped -> "ЭКИПИРОВАНО"
        ProfileText.ActiveRun -> "АКТИВНО В ЗАБЕГЕ"
        ProfileText.Equip -> "ЭКИПИРОВАТЬ"
        ProfileText.Unlock -> "ОТКРЫТЬ ЗА {0}"
        ProfileText.MasteryLevel -> "УР. {0} {1}"
        ProfileText.LabTitle -> "ЛАБОРАТОРИЯ"
        ProfileText.LabSummary -> "ПОСТОЯННЫЕ УЛУЧШЕНИЯ // МАТЕРИЯ: {0}"
        ProfileText.Rank -> "РАНГ {0}/{1}"
        ProfileText.MaximumSynchrony -> "МАКСИМАЛЬНЫЙ РАНГ"
        ProfileText.BuyMatter -> "КУПИТЬ ЗА {0} МАТЕРИИ"
        ProfileText.RebirthTitle -> "ПЕРЕРОЖДЕНИЕ"
        ProfileText.ThreatTier -> "ПОСТОЯННАЯ УГРОЗА // СТУПЕНЬ {0} > {1}"
        ProfileText.CurrentCycle -> "ТЕКУЩИЙ ЦИКЛ"
        ProfileText.NextCycle -> "СЛЕДУЮЩИЙ ЦИКЛ"
        ProfileText.ResetBuild -> "СБРОС: СБОРКА ЗАБЕГА"
        ProfileText.Kept -> "СОХРАНЯТСЯ: МАТЕРИЯ // ЛАБОРАТОРИЯ // АРСЕНАЛ // СПРАВОЧНИК"
        ProfileText.LifetimeKept -> "ВСЕ ОТКРЫТИЯ И НАСТРОЙКИ ТОЖЕ СОХРАНЯТСЯ"
        ProfileText.MaxRebirth -> "МАКСИМАЛЬНАЯ СТУПЕНЬ"
        ProfileText.LockedRebirth -> "ПЕРЕРОЖДЕНИЕ НЕДОСТУПНО"
        ProfileText.ConfirmRebirth -> "ПОДТВЕРДИТЬ // ПЕРЕЙТИ НА СТУПЕНЬ {0}"
        ProfileText.ArmRebirth -> "ПЕРЕРОДИТЬСЯ // СТУПЕНЬ {0} > {1}"
        ProfileText.AllDirectives -> "ВСЕ ДИРЕКТИВЫ УГРОЗЫ ПРОЙДЕНЫ"
        ProfileText.DefeatArchitect -> "ПОБЕДИТЕ АРХИТЕКТОРА НА СТУПЕНИ {0}"
        ProfileText.SecondPress -> "ПОВТОРНОЕ НАЖАТИЕ СБРОСИТ СБОРКУ ЗАБЕГА"
        ProfileText.FirstPress -> "ПЕРВОЕ НАЖАТИЕ ЗАПРОСИТ ПОДТВЕРЖДЕНИЕ"
        ProfileText.TierDirective -> "СТУПЕНЬ {0} // {1}"
        ProfileText.HostileEscalation -> "УСИЛЕНИЕ ВРАГОВ"
        ProfileText.OpeningHostiles -> "ВРАГОВ НА СТАРТЕ"
        ProfileText.EnemyCap -> "ЛИМИТ ВРАГОВ"
        ProfileText.SpawnRate -> "ЧАСТОТА ПОЯВЛЕНИЯ"
        ProfileText.EnemyIntegrity -> "ПРОЧНОСТЬ ВРАГОВ"
        ProfileText.EnemySpeed -> "СКОРОСТЬ ВРАГОВ"
        ProfileText.IncomingDamage -> "ВХОДЯЩИЙ УРОН"
        ProfileText.CycleCompensation -> "БОНУСЫ ЦИКЛА"
        ProfileText.ThreatAdvance -> "ОПЕРЕЖЕНИЕ УГРОЗЫ"
        ProfileText.PlayerPower -> "МОЩЬ ИГРОКА"
        ProfileText.CoreIntegrity -> "ПРОЧНОСТЬ ЯДРА"
        ProfileText.KineticMatter -> "КИНЕТИЧЕСКАЯ МАТЕРИЯ"
        ProfileText.BonusRerolls -> "ДОП. ПЕРЕВЫБОРЫ"
        ProfileText.Seconds -> "+{0} с"
    }
}
