// SPDX-FileCopyrightText: 2026 Vladislav Tomilov
// SPDX-License-Identifier: GPL-3.0-or-later

package kinetickk.ball.profile.interaction.localization

internal object RussianProfileText {
    operator fun get(key: ProfileText): String = when (key) {
        ProfileText.SettingsInterface -> "Интерфейс"
        ProfileText.RunStatisticsSide -> "Статистика забега"
        ProfileText.LeftSide -> "Слева"
        ProfileText.RightSide -> "Справа"
        ProfileText.PreviousPage -> "Предыдущая страница"
        ProfileText.NextPage -> "Следующая страница"
        ProfileText.SettingsTitle -> "Настройки"
        ProfileText.SettingsGame -> "Игра"
        ProfileText.SettingsSound -> "Звук"
        ProfileText.VolumePercent -> "Громкость в процентах, 0–100"
        ProfileText.SettingsGraphics -> "Графика"
        ProfileText.Language -> "Язык"
        ProfileText.Sfx -> "Звуки"
        ProfileText.Music -> "Музыка"
        ProfileText.MasterVolume -> "Общая громкость"
        ProfileText.SimulationSpeed -> "Скорость игры"
        ProfileText.TextSize -> "Размер текста"
        ProfileText.ScreenShake -> "Тряска экрана"
        ProfileText.Particles -> "Частицы"
        ProfileText.DamageNumbers -> "Числа урона"
        ProfileText.DamageNumberSize -> "Размер чисел"
        ProfileText.DamageNumberFormat -> "Формат чисел"
        ProfileText.DamageColorTiers -> "Цвет урона"
        ProfileText.On -> "Вкл"
        ProfileText.Off -> "Выкл"
        ProfileText.Low -> "Мало"
        ProfileText.Normal -> "Норма"
        ProfileText.High -> "Много"
        ProfileText.Small -> "Малый"
        ProfileText.Large -> "Крупный"
        ProfileText.Huge -> "Огромный"
        ProfileText.Compact -> "Кратко"
        ProfileText.Full -> "Полно"
        ProfileText.ArmoryTitle -> "Арсенал"
        ProfileText.LabTitle -> "Улучшения"
        ProfileText.MaximumSynchrony -> "Максимум"
        ProfileText.RebirthTitle -> "Перерождение"
        ProfileText.HostileEscalation -> "Усиление врагов"
        ProfileText.OpeningHostiles -> "Врагов на старте"
        ProfileText.EnemyCap -> "Лимит врагов"
        ProfileText.SpawnRate -> "Частота появления"
        ProfileText.EnemyIntegrity -> "Прочность врагов"
        ProfileText.EnemySpeed -> "Скорость врагов"
        ProfileText.IncomingDamage -> "Входящий урон"
        ProfileText.CycleCompensation -> "Бонусы цикла"
        ProfileText.ThreatAdvance -> "Опережение угрозы"
        ProfileText.PlayerPower -> "Мощь игрока"
        ProfileText.CoreIntegrity -> "Прочность ядра"
        ProfileText.KineticMatter -> "Кинетическая материя"
        ProfileText.BonusRerolls -> "Доп. перевыборы"
        ProfileText.Seconds -> "+{0} с"
    }
}
