// SPDX-FileCopyrightText: 2026 Vladislav Tomilov
// SPDX-License-Identifier: GPL-3.0-or-later

package kinetickk.ball.profile.interaction.localization

internal object RussianProfileText {
    operator fun get(key: ProfileText): String = when (key) {
        ProfileText.SettingsInterface -> "Интерфейс"
        ProfileText.RunStatisticsSide -> "Статистика забега"
        ProfileText.LeftSide -> "Слева"
        ProfileText.RightSide -> "Справа"
        ProfileText.Back -> "Назад · Esc"
        ProfileText.PreviousPage -> "Предыдущая страница"
        ProfileText.NextPage -> "Следующая страница"
        ProfileText.SettingsTitle -> "Настройки"
        ProfileText.SettingsHint -> "− / + изменить"
        ProfileText.SettingsGame -> "Игра"
        ProfileText.SettingsSound -> "Звук"
        ProfileText.SettingsSoundHint -> "Ползунок или ввод числа 0–100%"
        ProfileText.VolumePercent -> "Громкость в процентах, 0–100"
        ProfileText.SettingsGraphics -> "Графика"
        ProfileText.SettingsDamageHint -> "− / + изменить // урон: жёлтый > красный"
        ProfileText.Language -> "Язык"
        ProfileText.Sfx -> "Звуки"
        ProfileText.Music -> "Музыка"
        ProfileText.MasterVolume -> "Общая громкость"
        ProfileText.SimulationSpeed -> "Скорость игры"
        ProfileText.TextSize -> "Размер текста"
        ProfileText.ScreenShake -> "Тряска экрана"
        ProfileText.Particles -> "Частицы"
        ProfileText.DamageNumbers -> "Числа урона"
        ProfileText.DamageNumberSize -> "Размер чисел"
        ProfileText.DamageNumberFormat -> "Формат чисел"
        ProfileText.DamageColorTiers -> "Цвет урона"
        ProfileText.On -> "Вкл"
        ProfileText.Off -> "Выкл"
        ProfileText.Low -> "Мало"
        ProfileText.Normal -> "Норма"
        ProfileText.High -> "Много"
        ProfileText.Small -> "Малый"
        ProfileText.Large -> "Крупный"
        ProfileText.Huge -> "Огромный"
        ProfileText.Compact -> "Кратко"
        ProfileText.Full -> "Полно"
        ProfileText.ArmoryTitle -> "Арсенал"
        ProfileText.ArmorySummary -> "Открыто {1}/{0} · Материя {2}"
        ProfileText.Milestones -> "Мастерство усиливает урон и активацию"
        ProfileText.Equipped -> "Экипировано"
        ProfileText.ActiveRun -> "Активно в забеге"
        ProfileText.Equip -> "Экипировать"
        ProfileText.Unlock -> "Открыть за {0}"
        ProfileText.MasteryLevel -> "Ур. {0} {1}"
        ProfileText.LabTitle -> "Улучшения"
        ProfileText.LabSummary -> "Материя {0}"
        ProfileText.Rank -> "{0}/{1}"
        ProfileText.MaximumSynchrony -> "Максимум"
        ProfileText.BuyMatter -> "{0} ◇"
        ProfileText.RebirthTitle -> "Перерождение"
        ProfileText.ThreatTier -> "Ступень {0} → {1}"
        ProfileText.CurrentCycle -> "Сейчас"
        ProfileText.NextCycle -> "Далее"
        ProfileText.ResetBuild -> "Сборка забега будет сброшена"
        ProfileText.Kept -> "Материя, улучшения и открытое оружие сохранятся"
        ProfileText.LifetimeKept -> "Открытия и настройки сохранятся"
        ProfileText.MaxRebirth -> "Максимальная ступень"
        ProfileText.LockedRebirth -> "Перерождение недоступно"
        ProfileText.ConfirmRebirth -> "Подтвердить переход на ступень {0}"
        ProfileText.ArmRebirth -> "Перейти на ступень {1}"
        ProfileText.AllDirectives -> "Все директивы угрозы пройдены"
        ProfileText.DefeatArchitect -> "Победите архитектора на ступени {0}"
        ProfileText.SecondPress -> "Повторное нажатие сбросит сборку забега"
        ProfileText.FirstPress -> "Первое нажатие запросит подтверждение"
        ProfileText.TierDirective -> "{0} · {1}"
        ProfileText.HostileEscalation -> "Усиление врагов"
        ProfileText.OpeningHostiles -> "Врагов на старте"
        ProfileText.EnemyCap -> "Лимит врагов"
        ProfileText.SpawnRate -> "Частота появления"
        ProfileText.EnemyIntegrity -> "Прочность врагов"
        ProfileText.EnemySpeed -> "Скорость врагов"
        ProfileText.IncomingDamage -> "Входящий урон"
        ProfileText.CycleCompensation -> "Бонусы цикла"
        ProfileText.ThreatAdvance -> "Опережение угрозы"
        ProfileText.PlayerPower -> "Мощь игрока"
        ProfileText.CoreIntegrity -> "Прочность ядра"
        ProfileText.KineticMatter -> "Кинетическая материя"
        ProfileText.BonusRerolls -> "Доп. перевыборы"
        ProfileText.Seconds -> "+{0} с"
    }
}
